
from django.db import models
from django.contrib.auth.models import User

from django.conf import settings

USER_TYPE = (
    ('admin', 'Admin'),
    ('employer', 'Employer'),
    ('job_seeker', 'Job Seeker'),
)
GENDER = (
    ('male', 'Male'),
    ('female', 'Female'),
)
CURRENCY = (
    ('US Dollars','US Dollars'),
    ('UK Pound','UK Pound'),
    ('Indian Rupees', 'Indian Rupees'),
    ('UAE Dirham','UAE Dirham'),
    ('Dinar', 'Dinar'),       
    ('Riyal','Riyal'),
    ('Australian Dollars','Australian Dollars'),
    ('Singapore Dollars','Singapore Dollars'),
    ('Sri Lankan Rupee','Sri Lankan Rupee'),
    ('Euro',  'Euro'),      
    ('Yen', 'Yen'),      
    )
COUNTRY_CHOICES = (
    ('Afghanistan', 'Afghanistan'),
    ('Akrotiri', 'Akrotiri'),
    ('Albania','Albania'),
    ('Algeria','Algeria'),
    ('American Samoa','American Samoa'),
    ('Andorra','Andorra'),
    ('Anguilla','Anguilla'),
    ('Antartica','Antartica'),
    ('Antigua and Barbuda','Antigua and Barbuda'),
    ('Argentina','Argentina'),
    ('Armenia','Armenia'),
    ('Aruba','Aruba'),
    ('Ashmore and Cartier Islands','Ashmore and Cartier Islands'),
    ('Australia','Australia'),
    ('Austria','Austria'),
    ('Azerbaijan', 'Azerbaijan'),
    ('Bahamas','Bahamas'),
    ('Bahrain','Bahrain'),
    ('Bangladesh','Bangladesh'),
    ('Barbados','Barbados'),
    ('Bassas da India','Bassas da India'),
    ('Belarus','Belarus'),
    ('Belgium','Belgium'),
    ('Belize','Belize'),
    ('Benin','Benin'),
    ('Bermuda','Bermuda'),
    ('Bhutan','Bhutan'),
    ('Bolivia','Bolivia'),
    ('Bosnia and Herzegovina','Bosnia and Herzegovina'),
    ('Botswana','Botswana'),
    ('Bouvet Island','Bouvet Island'),
    ('Brazil','Brazil'),
    ('British Indian Ocean Territory','British Indian Ocean Territory'),
    ('British Virgin Islands','British Virgin Islands'),
    ('Brunei','Brunei'),
    ('Bulgaria','Bulgaria'),
    ('Burkina Faso','Burkina Faso'),
    ('Burma','Burma'),
    ('Burundi','Burundi'),
    ('Cambodia','Cambodia'),
    ('Cameroon','Cameroon'),
    ('Canada','Canada'),
    ('Cape Verde','Cape Verde'),
    ('Cayman Islands','Cayman Islands'),
    ('Central African Republic','Central African Republic'),
    ('Chad','Chad'),
    ('Chile','Chile'),
    ('China','China'),
    ('Christmas Island','Christmas Island'),
    ('Clipperton Island','Clipperton Island'),
    ('Cocos (Keeling) Islands','Cocos (Keeling) Islands'),
    ('Colombia','Colombia'),
    ('Comoros','Comoros'),
    ('Congo, Democratic Republic of the','Congo, Democratic Republic of the'),
    ('Congo, Republic of the','Congo, Republic of the'),
    ('Cook Islands','Cook Islands'),
    ('Coral Sea Islands','Coral Sea Islands'),
    ('Costa Rica','Costa Rica'),
    ( "Cote d'Ivoire", "Cote d'Ivoire"),
    ('Croatia','Croatia'),
    ('Cuba','Cuba'),
    ('Cyprus','Cyprus'),
    ('Czech Republic','Czech Republic'),
    ('Denmark','Denmark'),
    ('Dhekelia','Dhekelia'),
    ('Djibouti','Djibouti'),
    ('Dominica','Dominica'),
    ('Dominican Republic','Dominican Republic'),
    ('Ecuador','Ecuador'),
    ('Egypt','Egypt'),
    ('El Salvador','El Salvador'),
    ('Equatorial Guinea','Equatorial Guinea'),
    ('Eritrea','Eritrea'),
    ('Estonia','Estonia'),
    ('Ethiopia','Ethiopia'),
    ('Europa Island','Europa Island'),
    ('Falkland Islands (Islas Malvinas)','Falkland Islands (Islas Malvinas)'),
    ('Faroe Islands','Faroe Islands'),
    ('Fiji','Fiji'),
    ('Finland','Finland'),
    ('France','France'),
    ('French Guiana','French Guiana'),
    ('French Polynesia','French Polynesia'),
    ('French Southern and Antarctic Lands','French Southern and Antarctic Lands'),
    ('Gabon','Gabon'),
    ('Gambia, The','Gambia, The'),
    ('Gaza Strip','Gaza Strip'),
    ('Georgia','Georgia'),
    ('Germany','Germany'),
    ('Ghana','Ghana'),
    ('Gibraltar','Gibraltar'),
    ('Glorioso Islands','Glorioso Islands'),
    ('Greece','Greece'),
    ('Greenland','Greenland'),
    ('Grenada','Grenada'),
    ('Guadeloupe','Guadeloupe'),
    ('Guam','Guam'),
    ('Guatemala','Guatemala'),
    ('Guernsey','Guernsey'),
    ('Guinea','Guinea'),
    ('Guinea-Bissau','Guinea-Bissau'),
    ('Guyana','Guyana'),
    ('Haiti','Haiti'),
    ('Heard Island and McDonald Islands','Heard Island and McDonald Islands'),
    ('Holy See (Vatican City)','Holy See (Vatican City)'),
    ('Honduras','Honduras'),
    ('Hong Kong','Hong Kong'),
    ('Hungary','Hungary'),
    ('Iceland','Iceland'),
    ('India','India'),
    ('Indonesia','Indonesia'),
    ('Iran','Iran'),
    ('Iraq','Iraq'),
    ('Ireland','Ireland'),
    ('Isle of Man','Isle of Man'),
    ('Israel','Israel'),
    ('Italy','Italy'),
    ('Jamaica','Jamaica'),
    ('Jan Mayen','Jan Mayen'),
    ('Japan','Japan'),
    ('Jersey','Jersey'),
    ('Jordan','Jordan'),
    ('Juan de Nova Island','Juan de Nova Island'),
    ('Kazakhstan','Kazakhstan'),
    ('Kenya','Kenya'),
    ('Kiribati','Kiribati'),
    ('Korea, North','Korea, North'),
    ('Korea, South','Korea, South'),
    ('Kuwait','Kuwait'),
    ('Kyrgyzstan','Kyrgyzstan'),
    ('Laos','Laos'),
    ('Latvia','Latvia'),
    ('Lebanon','Lebanon'),
    ('Lesotho','Lesotho'),
    ('Liberia','Liberia'),
    ('Libya','Libya'),
    ('Liechtenstein','Liechtenstein'),
    ('Lithuania','Lithuania'),
    ('Luxembourg','Luxembourg'),
    ('Macau','Macau'),
    ('Macedonia','Macedonia'),
    ('Madagascar','Madagascar'),
    ('Malawi','Malawi'),
    ('Malaysia','Malaysia'),
    ('Maldives','Maldives'),
    ('Mali','Mali'),
    ('Malta','Malta'),
    ('Marshall Islands','Marshall Islands'),
    ('Martinique','Martinique'),
    ('Mauritania','Mauritania'),
    ('Mauritius','Mauritius'),
    ('Mayotte','Mayotte'),
    ('Mexico','Mexico'),
    ('Micronesia, Federated States of','Micronesia, Federated States of'),
    ('Moldova','Moldova'),
    ('Monaco','Monaco'),
    ('Mongolia','Mongolia'),
    ('Montserrat','Montserrat'),
    ('Morocco','Morocco'),
    ('Mozambique','Mozambique'),
    ('Namibia','Namibia'),
    ('Nauru','Nauru'),
    ('Navassa Island','Navassa Island'),
    ('Nepal','Nepal'),
    ('Netherlands','Netherlands'),
    ('Netherlands Antilles','Netherlands Antilles'),
    ('New Caledonia','New Caledonia'),
    ('New Zealand','New Zealand'),
    ('Nicaragua','Nicaragua'),
    ('Niger','Niger'),
    ('Nigeria','Nigeria'),
    ('Niue','Niue'),
    ('Norfolk Island','Norfolk Island'),
    ('Northern Mariana Islands','Northern Mariana Islands'),
    ('Norway','Norway'),
    ('Oman','Oman'),
    ('Pakistan','Pakistan'),
    ('Palau','Palau'),
    ('Panama','Panama'),
    ('Papua New Guinea','Papua New Guinea'),
    ('Paracel Islands','Paracel Islands'),
    ('Paraguay','Paraguay'),
    ('Peru','Peru'),
    ('Philippines','Philippines'),
    ('Pitcairn Islands','Pitcairn Islands'),
    ('Poland','Poland'),    
    ('Portugal','Portugal'),
    ('Puerto Rico','Puerto Rico'),
    ('Qatar','Qatar'),
    ('Reunion','Reunion'),
    ('Romania','Romania'),
    ('Russia','Russia'),
    ('Rwanda','Rwanda'),
    ('Saint Helena','Saint Helena'),
    ('Saint Kitts and Nevis','Saint Kitts and Nevis'),
    ('Saint Lucia','Saint Lucia'),
    ('Saint Pierre and Miquelon','Saint Pierre and Miquelon'),
    ('Saint Vincent and the Grenadines','Saint Vincent and the Grenadines'),
    ('Samoa','Samoa'),
    ('San Marino','San Marino'),
    ('Sao Tome and Principe','Sao Tome and Principe'),
    ('Saudi Arabia','Saudi Arabia'),
    ('Senegal','Senegal'),
    ('Serbia and Montenegro','Serbia and Montenegro'),
    ('Seychelles','Seychelles'),
    ('Sierra Leone','Sierra Leone'),
    ('Singapore','Singapore'),
    ('Slovakia','Slovakia'),
    ('Slovenia','Slovenia'),
    ('Solomon Islands','Solomon Islands'),
    ('Somalia','Somalia'),
    ('South Africa','South Africa'),
    ('South Georgia and the South Sandwich Islands','South Georgia and the South Sandwich Islands'),
    ('Spain','Spain'),
    ('Spratly Islands','Spratly Islands'),
    ('Sri Lanka','Sri Lanka'),
    ('Sudan','Sudan'),
    ('Suriname','Suriname'),
    ('Svalbard','Svalbard'),
    ('Swaziland','Swaziland'),
    ('Sweden','Sweden'),
    ('Switzerland','Switzerland'),
    ('Syria','Syria'),
    ('Taiwan','Taiwan'),
    ('Tajikistan','Tajikistan'),
    ('Tanzania','Tanzania'),
    ('Thailand','Thailand'),
    ('Timor-Leste','Timor-Leste'),
    ('Togo','Togo'),
    ('Tokelau','Tokelau'),
    ('Tonga','Tonga'),
    ('Trinidad and Tobago','Trinidad and Tobago'),
    ('Tromelin Island','Tromelin Island'),
    ('Tunisia','Tunisia'),
    ('Turkey','Turkey'),
    ('Turkmenistan','Turkmenistan'),
    ('Turks and Caicos Islands','Turks and Caicos Islands'),
    ('Tuvalu','Tuvalu'),
    ('Uganda','Uganda'),
    ('Ukraine','Ukraine'),
    ('United Arab Emirates','United Arab Emirates'),
    ('United Kingdom','United Kingdom'),
    ('United States','United States'),
    ('Uruguay','Uruguay'),
    ('Uzbekistan','Uzbekistan'),
    ('Vanuatu','Vanuatu'),
    ('Venezuela','Venezuela'),
    ('Vietnam','Vietnam'),
    ('Virgin Islands','Virgin Islands'),
    ('Wake Island','Wake Island'),
    ('Wallis and Futuna','Wallis and Futuna'),
    ('West Bank','West Bank'),
    ('Western Sahara','Western Sahara'),
    ('Yemen','Yemen'),
    ('Zambia','Zambia'),
    ('Zimbabwe','Zimbabwe'),
    ('Other', 'Other'),
)

NATIONALITY = (
    ('Afganistani', 'Afganistani'),
    ('Albanian', 'Albanian'),
    ('Algerian', 'Algerian'),
    ('American Samoa', 'American Samoa'),
    ('Andorra', 'Andorra'),
    ('Angola', 'Angola'),
    ('Anguilla', 'Anguilla'),
    ('Antarctican', 'Antarctican'),
    ('Antigua and Barbuda', 'Antigua and Barbuda'),
    ('Argentina', 'Argentina'),
    ('Armenian', 'Armenian'),
    ('Aruba', 'Aruba'),
    ('Australian', 'Australian'),
    ('Austrian', 'Austrian'),
    ('Azerbaijan', 'Azerbaijan'),
    ('Bahamas', 'Bahamas'),
    ('Bahraini', 'Bahraini'),
    ('Bangladeshi', 'Bangladeshi'),
    ('Barbados', 'Barbados'),
    ('Belarus', 'Belarus'),
    ('Belgium', 'Belgium'),
    ('Belize', 'Belize'),
    ('Benin', 'Benin'),
    ('Bermuda', 'Bermuda'),
    ('Bhutani', 'Bhutani'),
    ('Bolivian', 'Bolivian'),
    ('Bosnia and Herzegovinan', 'Bosnia and Herzegovinan'),
    ('Botswana', 'Botswana'),
    ('Bouvet Island', 'Bouvet Island'),
    ('Brazilian', 'Brazilian'),
    ('British Indian Ocean Territory', 'British Indian Ocean Territory'),
    ('Brunei Darussalam', 'Brunei Darussalam'),
    ('Bulgarian', 'Bulgarian'),
    ('Burkina Faso', 'Burkina Faso'),
    ('Burundi', 'Burundi'),
    ('Cambodian', 'Cambodian'),
    ('Cameroon', 'Cameroon'),
    ('Canadian', 'Canadian'),
    ('Cape Verde', 'Cape Verde'),
    ('Cayman Islands', 'Cayman Islands'),
    ('Central African Republic', 'Central African Republic'),
    ('Chad', 'Chad'),
    ('Chile', 'Chile'),
    ('Chinese', 'Chinese'),
    ('Christmas Island', 'Christmas Island'),
    ('Cocos (Keeling) Islands', 'Cocos (Keeling) Islands'),
    ('Colombian', 'Colombian'),
    ('Comoros', 'Comoros'),
    ('Congo', 'Congo'),
    ('Cook Islands', 'Cook Islands'),
    ('Costa Rica', 'Costa Rica'),
    ("Cote D'Ivoire", "Cote D'Ivoire"),
    ('Croatia', 'Croatia'),
    ('Cuban', 'Cuban'),
    ('Cyprus', 'Cyprus'),
    ('Czech Republic', 'Czech Republic'),
    ('Denmark', 'Denmark'),
    ('Djibouti', 'Djibouti'),
    ('Dominica', 'Dominica'),
    ('Dominican Republic', 'Dominican Republic'),
    ('Ecuador', 'Ecuador'),
    ('Egyptian', 'Egyptian'),
    ('El Salvador', 'El Salvador'),
    ('Emirati', 'Emirati'),
    ('Equatorial Guinea', 'Equatorial Guinea'),
    ('Eritrea', 'Eritrea'),
    ('Estonia', 'Estonia'),
    ('Ethiopian', 'Ethiopian'),
    ('Falkland Islands (Malvinas)', 'Falkland Islands (Malvinas)'),
    ('Faroe Islands', 'Faroe Islands'),
    ('Fiji', 'Fiji'),
    ('Filipino', 'Filipino'),
    ('Finland', 'Finland'),
    ('French', 'French'),
    ('French Guiana', 'French Guiana'),
    ('French Polynesia', 'French Polynesia'),
    ('French Southern Territories', 'French Southern Territories'),
    ('Gabon', 'Gabon'),
    ('Georgian', 'Georgian'),
    ('German', 'German'),
    ('Ghana', 'Ghana'),
    ('Gibraltar', 'Gibraltar'),
    ('Greece', 'Greece'),
    ('Greenland', 'Greenland'),
    ('Grenada', 'Grenada'),
    ('Guadeloupe', 'Guadeloupe'),
    ('Guam', 'Guam'),
    ('Guinean', 'Guinean'),
    ('Guinea-Bissau', 'Guinea-Bissau'),
    ('Guyana', 'Guyana'),
    ('Haiti', 'Haiti'),
    ('Heard Island and Mcdonald Islands', 'Heard Island and Mcdonald Islands'),
    ('Holy See (Vatican City State)', 'Holy See (Vatican City State)'),
    ('Honduras', 'Honduras'),
    ('Hong Kong', 'Hong Kong'),
    ('Hungarian', 'Hungarian'),
    ('Iceland', 'Iceland'),
    ('Indian', 'Indian'),
    ('Indonesian', 'Indonesian'),
    ('Iranian', 'Iranian'),
    ('Ireland', 'Ireland'),
    ('Israeli', 'Israeli'),
    ('Japanese', 'Japanese'),
    ('Jordanian', 'Jordanian'),
    ('Kazakhstani', 'Kazakhstani'),
    ('Kenyan', 'Kenyan'),
    ('Kiribati', 'Kiribati'),
    ("Korea, Democratic People's Republic of", "Korea, Democratic People's Republic of"),
    ('Korea, Republic of', 'Korea, Republic of'),
    ('Kuwaiti', 'Kuwaiti'),
    ('Kyrgyzstani', 'Kyrgyzstani'),
    ("Lao People's Democratic Republic", "Lao People's Democratic Republic"),
    ('Latvian', 'Latvian'),
    ('Lebanese', 'Lebanese'),
    ('Lesotho', 'Lesotho'),
    ('Liberian', 'Liberian'),
    ('Libyan Arab Jamahiriya', 'Libyan Arab Jamahiriya'),
    ('Liechtenstein', 'Liechtenstein'),
    ('Lithuania', 'Lithuania'),
    ('Luxembourg', 'Luxembourg'),
    ('Macao', 'Macao'),
    ('Macedonia, the Former Yugoslav Republic of', 'Macedonia, the Former Yugoslav Republic of'),
    ('Madagascar', 'Madagascar'),
    ('Malawi', 'Malawi'),
    ('Malaysian', 'Malaysian'),
    ('Maldives', 'Maldives'),
    ('Mali', 'Mali'),
    ('Malta', 'Malta'),
    ('Marshall Islands', 'Marshall Islands'),
    ('Martinique', 'Martinique'),
    ('Mauritanian', 'Mauritanian'),
    ('Mauritius', 'Mauritius'),
    ('Mayotte', 'Mayotte'),
    ('Mexican', 'Mexican'),
    ('Micronesia, Federated States of', 'Micronesia, Federated States of'),
    ('Moldova, Republic of', 'Moldova, Republic of'),
    ('Monaco', 'Monaco'),
    ('Mongolian', 'Mongolian'),
    ('Montserrat', 'Montserrat'),
    ('Moroccan', 'Moroccan'),
    ('Mozambique', 'Mozambique'),
    ('Myanmar', 'Myanmar'),
    ('Namibia', 'Namibia'),
    ('Nauru', 'Nauru'),
    ('Nepalese', 'Nepalese'),
    ('Netherlands', 'Netherlands'),
    ('Netherlands Antilles', 'Netherlands Antilles'),
    ('New Caledonia', 'New Caledonia'),
    ('New Zealand', 'New Zealand'),
    ('Nicaragua', 'Nicaragua'),
    ('Niger', 'Niger'),
    ('Nigerian', 'Nigerian'),
    ('Niue', 'Niue'),
    ('Norfolk Island', 'Norfolk Island'),
    ('Northern Mariana Islan', 'Northern Mariana Islan'),
    ('Norway', 'Norway'),
    ('Omani', 'Omani'),
    ('Pakistani', 'Pakistani'),
    ('Palau', 'Palau'),
    ('Palestinian', 'Palestinian'),
    ('Panama', 'Panama'),
    ('Papua New Guinea', 'Papua New Guinea'),
    ('Paraguay', 'Paraguay'),
    ('Peru', 'Peru'),
    ('Pitcairn', 'Pitcairn'),
    ('Poland', 'Poland'),
    ('Portugal', 'Portugal'),
    ('Puerto Rico', 'Puerto Rico'),
    ('Qatari', 'Qatari'),
    ('Reunion', 'Reunion'),
    ('Romanian', 'Romanian'),
    ('Russian', 'Russian'),
    ('Rwanda', 'Rwanda'),
    ('Saint Helena', 'Saint Helena'),
    ('Saint Kitts and Nevis', 'Saint Kitts and Nevis'),
    ('Saint Lucia', 'Saint Lucia'),
    ('Saint Pierre and Miquelon', 'Saint Pierre and Miquelon'),
    ('Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines'),
    ('Samoa', 'Samoa'),
    ('San Marino', 'San Marino'),
    ('Sao Tome and Principe', 'Sao Tome and Principe'),
    ('Saudi', 'Saudi'),
    ('Senegal', 'Senegal'),
    ('Serbia and Montenegro', 'Serbia and Montenegro'),
    ('Seychelles', 'Seychelles'),
    ('Sierra Leone', 'Sierra Leone'),
    ('Singaporean', 'Singaporean'),
    ('Slovakian', 'Slovakian'),
    ('Slovenian', 'Slovenian'),
    ('Solomon - Islands   ', 'Solomon - Islands   '),
    ('Somalian', 'Somalian'),
    ('South African', 'South African'),
    ('South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands'),
    ('Spanish', 'Spanish'),
    ('Sri Lankan', 'Sri Lankan'),
    ('Sudanese', 'Sudanese'),
    ('Suriname', 'Suriname'),
    ('Svalbard and Jan Mayen', 'Svalbard and Jan Mayen'),
    ('Swaziland', 'Swaziland'),
    ('Sweden', 'Sweden'),
    ('Switzerland', 'Switzerland'),
    ('Syrian', 'Syrian'),
    ('Taiwanese', 'Taiwanese'),
    ('Tajikistan', 'Tajikistan'),
    ('Tanzania, United Republic of', 'Tanzania, United Republic of'),
    ('Thai', 'Thai'),
    ('Timor-Leste', 'Timor-Leste'),
    ('Togo', 'Togo'),
    ('Tokelau', 'Tokelau'),
    ('Tonga', 'Tonga'),
    ('Trinidad and Tobago', 'Trinidad and Tobago'),
    ('Tunisia', 'Tunisia'),
    ('Turkish', 'Turkish'),
    ('Turkmenistan', 'Turkmenistan'),
    ('Turks and Caicos Islands', 'Turks and Caicos Islands'),
    ('Tuvalu', 'Tuvalu'),
    ('Uganda', 'Uganda'),
    ('Ukraine', 'Ukraine'),
    ('United Kingdom', 'United Kingdom'),
    ('United States', 'United States'),
    ('United States Minor Outlying Islands', 'United States Minor Outlying Islands'),
    ('Uruguay', 'Uruguay'),
    ('Uzbekistani', 'Uzbekistani'),
    ('Vanuatu', 'Vanuatu'),
    ('Venezuela', 'Venezuela'),
    ('Vietnamese', 'Vietnamese'),
    ('Virgin Islands, British', 'Virgin Islands, British'),
    ('Virgin Islands, U.s.', 'Virgin Islands, U.s.'),
    ('Wallis and Futuna', 'Wallis and Futuna'),
    ('Western Sahara', 'Western Sahara'),
    ('Yemeni', 'Yemeni'),
    ('Zambian', 'Zambian'),
    ('Zimbabwe', 'Zimbabwe'),
    ('Other', 'Other'),

)


INDUSTRY = (
    ('Automotive/ Ancillaries', 'Automotive/ Ancillaries'),
    ('Banking/ Financial Services', 'Banking/ Financial Services'),
    ('Bio Technology & Life Sciences', 'Bio Technology & Life Sciences'),
    ('Chemicals/Petrochemicals', 'Bio Technology & Life Sciences'),
    ('Construction', 'Construction'),
    ('FMCG', 'FMCG'),
    ('Education', 'Education'),
    ('Entertainment/ Media/ Publishing', 'Entertainment/ Media/ Publishing'),
    ('Insurance', 'Insurance'),
    ('ITES/BPO', 'ITES/BPO'),
    ('IT/ Computers - Hardware', 'IT/ Computers - Hardware'),
    ('IT/ Computers - Software', 'IT/ Computers - Software'),
    ('KPO/Analytics', 'KPO/Analytics'),
    ('Machinery/ Equipment Mfg.', 'Machinery/ Equipment Mfg.'),
    ('Oil/ Gas/ Petroleum', 'Oil/ Gas/ Petroleum'),
    ('Pharmaceuticals', 'Pharmaceuticals'),
    ('Plastic/ Rubber', 'Plastic/ Rubber'),
    ('Power/Energy', 'Power/Energy'),
    ('Real Estate', 'Real Estate'),
    ('Retailing', 'Retailing'),
    ('Telecom', 'Telecom'),
    ('Advertising/PR/Events', 'Advertising/PR/Events'),
    ('Agriculture/ Dairy Based', 'Agriculture/ Dairy Based'),
    ('Aviation/Aerospace', 'Aviation/Aerospace'),
    ('Beauty/Fitness/PersonalCare/SPA', 'Beauty/Fitness/PersonalCare/SPA'),
    ('Beverages/ Liquor', 'Beverages/ Liquor'),
    ('Cement', 'Cement'),
    ('Ceramics & Sanitary Ware', 'Ceramics & Sanitary Ware'),
    ('Consultancy', 'Consultancy'),
    ('Courier/ Freight/ Transportation', 'Courier/ Freight/ Transportation'),
    ('Dotcom', 'Dotcom'),
    ('Electrical/Switchgear', 'Electrical/Switchgear'),
    ('Engineering, Procurement, Construction', 'Engineering, Procurement, Construction'),
    ('Environmental Service', 'Environmental Service'),
    ('Facility management', 'Facility management'),
    ('Fertilizer/ Pesticides', 'Fertilizer/ Pesticides'),
    ('Food & Packaged Food', 'Food & Packaged Food'),
    ('Textiles / Yarn / Fabrics / Garments', 'Textiles / Yarn / Fabrics / Garments'),
    ('Gems & Jewellery', 'Gems & Jewellery'),
    ('Government/ PSU/ Defence', 'Government/ PSU/ Defence'),
    ('Consumer Electronics/Appliances', 'Consumer Electronics/Appliances'),
    ('Hospitals/ Health Care', 'Hospitals/ Health Care'),
    ('Hotels/ Restaurant', 'Hotels/ Restaurant'),
    ('Import / Export', 'Import / Export'),
    ('Iron/ Steel', 'Iron/ Steel'),
    ('ISP', 'ISP'),
    ('Law Enforcement/Security Services', 'Law Enforcement/Security Services'),
    ('Leather', 'Leather'),
    ('Market Research','Market Research'),
    ('Med', 'Med'),
    ('Medical Transcription', 'Medical Transcription'),
    ('Mining', 'Mining'),
    ('NGO', 'NGO'),
    ('Non-Ferrous Metals (Aluminium, Zinc etc.)', 'Non-Ferrous Metals (Aluminium, Zinc etc.)'),
    ('Office Equipment/Automation', 'Office Equipment/Automation'),
    ('Paints', 'Paints'),
    ('Paper', 'Paper'),
    ('Printing/ Packaging', 'Printing/ Packaging'),
    ('Public Relations (PR)', 'Public Relations (PR)'),
    ('Shipping/ Marine Services', 'Shipping/ Marine Services'),
    ('Travel/ Tourism', 'Travel/ Tourism'),
    ('Tyres', 'Tyres'),
    ('Wood', 'Wood'),
    ('Other', 'Other'),
    ('Any', 'Any'),
)

FUNCTIONS = (
        ('Admin/Secretarial', 'Admin/Secretarial'),
        ('Customer Service/ Call Centre/ BPO', 'Customer Service/ Call Centre/ BPO'),
        ('Finance & Accounts', 'Finance & Accounts'),
        ('Human Resources', 'Human Resources'),
        ('IT', 'IT'),
        ('Legal', 'Legal'),
        ('Marketing & Communications', 'Marketing & Communications'),
        ('Purchase/ Logistics/ Supply Chain', 'Purchase/ Logistics/ Supply Chain'),
        ('Sales/ Business Development', 'Sales/ Business Development'),
        ('Advertising/Entertainment/Media', 'Advertising/Entertainment/Media'),
        ('Banking, Insurance & Financial Services', 'Banking, Insurance & Financial Services'),
        ('Construction', 'Construction'),
        ('Education/ Teaching', 'Education/ Teaching'),
        ('Export/ Import', 'Export/ Import'),
        ('Health Care', 'Health Care'),
        ('Hotels/ restaurants', 'Hotels/ restaurants'),
        ('Manufacturing/ Engineering/ R&D', 'Manufacturing/ Engineering/ R&D'),
        ('Oil & Gas', 'Oil & Gas'),
        ('Pharmaceutical/ Biotechnology', 'Pharmaceutical/ Biotechnology'),
        ('Analytics/Business Intelligence', 'Analytics/Business Intelligence'),
        ('Real Estate', 'Real Estate'),
        ('Retail Chains', 'Retail Chains'),
        ('Telecom/ ISP', 'Telecom/ ISP'),
        ('Travel/ Airlines', 'Travel/ Airlines'),     
        ('Others', 'Others'),
)

MARITAL_STATUS = (
    ('Single', 'Single'),
    ('Married', 'Married'),
    ('Divorced', 'Divorced'),
    ('Widow(er)', 'Widow(er)'),

)

RELIGION = (
    ('Islam', 'Islam'),
    ('Christian', 'Christian'),
    ('Hindu', 'Hindu'),
    ('Buddhist', 'Buddhist'),
    ('Sikh', 'Sikh'),
    ('Jain', 'Jain'),
    ('Zoroaster', 'Zoroaster'),
    ('Other', 'Other'),
    ('Do not wish to Disclose', 'Do not wish to Disclose'),
)


YEARS = (
    (0,'0'),
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
    (6, '6'),
    (7, '7'),
    (8, '8'),
    (9, '9'),
    (10, '10'),
    (11, '11'),
    (12, '12'),
    (13, '13'),
    (14, '14'),
    (15, '15'),
    (16, '16'),
    (17, '17'),
    (18, '18'),
    (19, '19'),
    (20, '20'),
    (21, '21'),
    (22, '22'),
    (23, '23'),
    (24, '24'),
    (25, '25'),
    (26, '26'),
    (27, '27'),
    (28, '28'),
    (29, '29'),
    (30, '30'),
    (31, '31'),
    (32, '32'),
    (33, '33'),
    (34, '34'),
    (35, '35'),
    (36, '36'),
    (37, '37'),
    (38, '38'),
    (39, '39'),
    (40, '40'),
    (41, '41'),
    (42, '42'),
    (43, '43'),
    (44, '44'),
    (45, '45'),
    (46, '46'),
    (47, '47'),
    (48, '48'),
    (49, '49'),
    (50, '50'),
)

MONTHS =(
    (0, '0'),
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
    (6, '6'),
    (7, '7'),
    (8, '8'),
    (9, '9'),
    (10, '10'),
    (11, '11'),

)


BASIC_EDU = (
    ('Diploma', 'Diploma'),
    ('Intermediate Schooling', 'Intermediate Schooling'),
    ('Secondary Schooling', 'Secondary Schooling'),   
    ('Bachelor of Architecture', 'Bachelor of Architecture'),
    ('Bachelor of Arts', 'Bachelor of Arts'),
    ('Bachelor of Business Administration', 'Bachelor of Business Administration'),
    ('Bachelor of Commerce', 'Bachelor of Commerce'),
    ('Bachelor of Dental Sugery', 'Bachelor of Dental Sugery'),
    ('Bachelor of Education', 'Bachelor of Education'),
    ('Bachelor of Hotel Management', 'Bachelor of Hotel Management'),
    ('Bachelor of Laws (LLB)', 'Bachelor of Laws (LLB)'),
    ('Bachelor of Pharmacy', 'Bachelor of Pharmacy'),
    ('Bachelor of Science', 'Bachelor of Science'),
    ('Bachelor of Technology/Engineering', 'Bachelor of Technology/Engineering'),
    ('Bachelor of Vetirenary Science', 'Bachelor of Vetirenary Science'),
    ('Bachelor of Computer Application', 'Bachelor of Computer Application'),
    ('MBBS', 'MBBS'),
    ('Other', 'Other'),
)
BASIC_SPEC = (
    ('General (College Proprietary)','General (College Proprietary)'),
    ('Academic / General','Academic / General'),
    ('Commercial','Commercial'),
    ('Technical','Technical'),
    ('Vocational','Vocational'),
    ('Religion','Religion'),
    ('Aircraft Maintenance','Aircraft Maintenance'),
    ('Autoclave Operation','Autoclave Operation'),
    ('Cement Technology','Cement Technology'),
    ('Chemical','Chemical'),
    ('Civil','Civil'),
    ('Computers ','Computers '),
    ('Drilling & Exploration Technology','Drilling & Exploration Technology'),
    ('Electrical','Electrical'),
    ('Electronics','Electronics'),
    ('Engineering','Engineering'),
    ('Export/Import','Export/Import'),
    ('Fashion Designing/Other Designing','Fashion Designing/Other Designing'),
    ('Foundry & Forging','Foundry & Forging'),
    ('Graphic/ Web Designing','Graphic/ Web Designing'),
    ('Hotel Management','Hotel Management'),
    ('Instrumentation & Control','Instrumentation & Control'),
    ('Insurance','Insurance'),
    ('Jewelery Design & Manufacturing','Jewelery Design & Manufacturing'),
    ('Machine Tool Maintenance & Repair','Machine Tool Maintenance & Repair'),
    ('Management','Management'),
    ('Mechanical','Mechanical'),
    ('Medical Instrumentation','Medical Instrumentation'),
    ('Medical Lab Technology','Medical Lab Technology'),
    ('Petrochemical Technology','Petrochemical Technology'),
    ('Process Instrumentation','Process Instrumentation'),
    ('Production Technology','Production Technology'),
    ('Refinery & Petro Chemical Technology','Refinery & Petro Chemical Technology'),
    ('Refrigeration & Airconditioning','Refrigeration & Airconditioning'),
    ('Surface Coating Technology','Surface Coating Technology'),
    ('Survey Engineering','Survey Engineering'),
    ('Telecommunication','Telecommunication'),
    ('Tool & Die Technology','Tool & Die Technology'),
    ('Tourism','Tourism'),
    ('Videography','Videography'),
    ('Visual Arts','Visual Arts'),
    ('Vocational Course','Vocational Course'),
    ('Welding Technology','Welding Technology'),
    ('Architecture','Architecture'),
    ('Arabic','Arabic'),
    ('Arts&Humanities','Arts&Humanities'),
    ('Communication','Communication'),
    ('Economics','Economics'),
    ('English','English'),
    ('Film','Film'),
    ('Fine arts','Fine arts'),
    ('Hindi','Hindi'),
    ('History','History'),
    ('Journalism','Journalism'),
    ('Middle Eastern Studies','Middle Eastern Studies'),
    ('Political Science','Political Science'),
    ('PR/Advertising','PR/Advertising'),
    ('Psychology','Psychology'),
    ('Religion','Religion'),
    ('Sociology','Sociology'),
    ('Statistics','Statistics'),
    ('Urdu','Urdu'),
    ('Management','Management'),
    ('Commerce','Commerce'),
    ('Dentistry','Dentistry'),
    ('Education','Education'),
    ('Religious Education','Religious Education'),
    ('Law','Law'),
    ('Pharmacy','Pharmacy'),
    ('Agriculture','Agriculture'),
    ('Anthropology','Anthropology'),
    ('Bio-Chemistry','Bio-Chemistry'),
    ('Biology','Biology'),
    ('Botany','Botany'),
    ('Chemistry','Chemistry'),
    ('Dairy','Dairy'),
    ('Technology','Technology'),
    ('Environmental science',''),
    ('Food Technology','Food Technology'),
    ('Geology','Geology'),
    ('Home Science','Home Science'),
    ('Maths','Maths'),
    ('Microbiology','Microbiology'),
    ('Nursing','Nursing'),
    ('Physics','Physics'),
    ('Statistics','Statistics'),
    ('Zoology','Zoology'),
    ('General','General'),
    ('Agriculture','Agriculture'),
    ('Automobile','Automobile'),
    ('Aviation','Aviation'),
    ('Bio-Technology','Bio-Technology'),
    ('Biomedical','Biomedical'),
    ('Ceramics','Ceramics'),
    ('Chemical','Chemical'),
    ('Civil','Civil'),
    ('Electronics/Telecomunication','Electronics/Telecomunication'),
    ('Energy','Energy'),
    ('Environmental','Environmental'),
    ('Instrumentation','Instrumentation'),
    ('Marine','Marine'),
    ('Mechanical','Mechanical'),
    ('Metallurgy','Metallurgy'),
    ('Mineral','Mineral'),
    ('Mining','Mining'),
    ('Nuclear','Nuclear'),
    ('Paint/Oil','Paint/Oil'),
    ('Petroleum','Petroleum'),
    ('Plastics','Plastics'),
    ('Production/Industrial','Production/Industrial'),
    ('Textile','Textile'),
    ('Other Engineering','Other Engineering'),
    ('Other', 'Other')

    )

FUNC_ROLE = (    
    ('Fresher', 'Fresher'),
    ('Travel/Immigration Coordinator', 'Travel/Immigration Coordinator'),
    ('Administration Executive', 'Administration Executive'),
    ('Computer Operator/ Data Entry', 'Computer Operator/ Data Entry'),
    ('Typist', 'Typist'),
    ('Despatch Incharge', 'Despatch Incharge'),
    ('Receptionist/ Front Desk', 'Receptionist/ Front Desk'),
    ('Secretarial', 'Secretarial'),
    ('Executive Secretary/Personal Assistant',' Executive Secretary/Personal Assistant'),
    ('Facilities Manager', 'Facilities Manager'),
    ('Administration Manager', 'Administration Manager'),
    ('VP/ GM - Administration', 'VP/ GM - Administration'),
    ('Other Admin/Clerical/Secretarial', 'Other Admin/Clerical/Secretarial'),
    ('Fresher', 'Fresher'),
    ('Trainee/ Management Trainee', 'Trainee/ Management Trainee'),
    ('Technical Support Executive ( voice)', 'Technical Support Executive ( voice)'),
    ('Technical Support Representative (Non- voice)', 'Technical Support Representative (Non- voice)'),
    ('Customer Service Executive (Voice)', 'Customer Service Executive (Voice)'),
    ('Customer Service Executive (Non-voice)',  'Customer Service Executive (Non-voice)'),
    ('Data Processing Executive', 'Data Processing Executive'),
    ('Telesales Executive', 'Telesales Executive'),
    ('Telemarketing Executive', 'Telemarketing Executive'),
    ('Manager - Data Processing', 'Manager - Data Processing'),
    ('Team Leader', 'Team Leader'),
    ('Medical Transcriptionist', 'Medical Transcriptionist'),
    ('Transactions Processing Executive', 'Transactions Processing Executive'),
    ('AR Caller/ AR Analyst', 'AR Caller/ AR Analyst'),
    ('Account Services Executive','Account Services Executive'),
    ('Operations Manager', 'Operations Manager'),
    ('Manager - Service Delivery', 'Manager - Service Delivery'),
    ('Technical Trainer', 'Technical Trainer'),
    ('Quality Assurance - Manager', 'Quality Assurance - Manager'),
    ('VP/ GM - Quality', 'VP/ GM - Quality'),
    ('Shift Supervisor', 'Shift Supervisor'),
    ('Training Manager', 'Training Manager'),
    ('Manager - Migrations/ Transitions', 'Manager - Migrati)ons/ Transitions'),
    ('Process/ Work Flow Analyst', 'Process/ Work Flow Analyst'),
    ('Quality Assurance Executive', 'Quality Assurance Executive'),
    ('Voice & Accent Trainer', 'Voice & Accent Trainer'),
    ('Process Trainer', 'Process Trainer'),
    ('Soft Skills Trainer', 'Soft Skills Trainer') ,
    ('VP/ Head - Customer Service', 'VP/ Head - Customer Service'),
    ('VP - Operations/ COO', 'VP - Operations/ COO'),
    ('SBU Head /Profit Centre Head', 'SBU Head /Profit Centre Head'),
    ('CEO/ MD/ Country Manager', 'CEO/ MD/ Country Manager'),
    ('Director on Board', 'Director on Board'),
    ('External Consultant', 'External Consultant'),
    ('Other Customer Service/ Call Center', 'Other Customer Service/ Call Center'),
    ('Fresher', 'Fresher'),
    ('Graduate Trainee/ Management Trainee', 'Graduate Trainee/ Management Trainee'),
    ('Book Keeper/ Accounts Assistant', 'Book Keeper/ Accounts Assistant'),
    ('Accountant', 'Accountant' ),
    ('Accounts Manager', 'Accounts Manager'),
    ('Cost Accountant / ICWA', 'Cost Accountant / ICWA'),
    ('Chartered Accountant (CPA)', 'Chartered Accountant (CPA)'),
    ('Accounts Head / GM - Accounts' , 'Accounts Head / GM - Accounts'),
    ('Finance Assistant', 'Finance Assistant'),
    ('Financial Controller', 'Financial Controller'),
    ('Manager - Financial Planning / Budgeting', 'Manager - Financial Planning / Budgeting'),
    ('Finance Manager', 'Finance Manager'),
    ('Financial/ Business Analyst', 'Financial/ Business Analyst'),
    ('Head / GM - Finance', 'Head / GM - Finance'),
    ('Internal Auditor', 'Internal Auditor'),
    ('External Auditor', 'External Auditor'),
    ('Commercial Executive/Manager', 'Commercial Executive/Manager'),
    ('Credit Control & Collections', 'Credit Control & Collections'),
    ('Treasury Manager', 'Treasury Manager'),
    ('Company Secretary', 'Company Secretary'),
    ('Taxation - Manager', 'Taxation - Manager'),
    ('Shares Services Executive', 'Shares Services Executive'),
    ('Business/ Strategic Planning - Manager', 'Business/ Strategic Planning - Manager'),
    ('Foreign Exchange Officer', 'Foreign Exchange Officer'),
    ('Payroll / Compensation Executive', 'Payroll / Compensation Executive'),
    ('Payroll / Compensation - Manager / Head', 'Payroll / Compensation - Manager / Head'),
    ('GM/Head/VP Corporate Planning/Strategy', 'GM/Head/VP Corporate Planning/Strategy'),
    ('VP Finance/ CFO', 'VP Finance/ CFO'),
    ('External Consultant', 'External Consultant'),
    ('Other Finance & Accounts', 'Other Finance & Accounts'),

    ('Fresher', 'Fresher'),
    ('Graduate Trainee / Management Trainee', 'Graduate Trainee / Management Trainee'),
    ('Payroll/ Compensation Executive', 'Payroll/ Compensation Executive'),
    ('HR Executive / Recruiter', 'HR Executive / Recruiter'),
    ('HR Manager', 'HR Manager'),
    ('HR Business Partner', 'HR Business Partner'),
    ('Training & Development Executive', 'Training & Development Executive'),
    ('Payroll/ Compensation - Head/ Mgr', 'Payroll/ Compensation - Head/ Mgr'),
    ('Recruitment - Head/ Mgr', 'Recruitment - Head/ Mgr'),
    ('Training & Development - Head/ Mgr', 'Training & Development - Head/ Mgr'),
    ('Appraisals - Head/ Mgr', 'Appraisals - Head/ Mgr'),
    ('Industrial Relations / Personnel Manager', 'Industrial Relations / Personnel Manager'),
    ('VP/ GM - HR', 'VP/ GM - HR'),
    ('External Consultant', 'External Consultant'),
    ('Other Human Resource', 'Other Human Resource'),


    ('Fresher' , 'Fresher'),
    ('Trainee' , 'Trainee'),
    ('Software Engineer/ Programmer' , 'Software Engineer/ Programmer'), 
    ('Systems Engineer', 'Systems Engineer'),
    ('Team Leader/ Technical Leader', 'Team Leader/ Technical Leader'),
    ('System Analyst/ Tech Architect', 'System Analyst/ Tech Architect'),
    ('Business Analyst', 'Business Analyst'),
    ('Project Leader/ Project Manager', 'Project Leader/ Project Manager'),
    ('Database Administrator (DBA)', 'Database Administrator (DBA)'),
    ('Database Architect/ Designer', 'Database Architect/ Designer'),
    ('Delivery Manager', 'Delivery Manager'),
    ('Program Manager', 'Program Manager'),
    ('Datawarehousing Consultants', 'Datawarehousing Consultants'),
    ('System Administrator', 'System Administrator'),
    ('H/W Installation/ Maintenance Engg', 'H/W Installation/ Maintenance Engg'),
    ('Network Administrator', 'Network Administrator'),
    ('Network Designer', 'Network Designer'),
    ('Security Analyst', 'Security Analyst'),
    ('System Security - Engineer', 'System Security - Engineer'),
    ('Technical Support Engineer', 'Technical Support Engineer'),
    ('Software Test Engineer', 'Software Test Engineer'),
    ('System Integrator', 'System Integrator'),
    ('Graphic Designer/ Animator', 'Graphic Designer/ Animator'),
    ('ERP, CRM - Functional Consultant', 'ERP, CRM - Functional Consultant'),
    ('ERP, CRM - Technical Consultant', 'ERP, CRM - Technical Consultant'),
    ('ERP, CRM - Support Engineer', 'ERP, CRM - Support Engineer'),
    ('S/W Installation/ Maintenance Engg', 'S/W Installation/ Maintenance Engg'),
    ('Product Manager', 'Product Manager'),
    ('Configuration Mgr/ Release Manager', 'Configuration Mgr/ Release Manager'),
    ('Trainer/ Faculty', 'Trainer/ Faculty'),
    ('Technical Writer', 'Technical Writer'),
    ('VP/ GM - Quality', 'VP/ GM - Quality'),
    ('Web Master/ Web Site Manager', 'Web Master/ Web Site Manager'),
    ('SEO Expert', 'SEO Expert'),
    ('Hardware Design Engineer', 'Hardware Design Engineer'),
    ('Hardware Design Technical Leader', 'Hardware Design Technical Leader'),
    ('Quality Assurance Executive', 'Quality Assurance Executive'),
    ('Quality Assurance - Manager', 'Quality Assurance - Manager'),
    ('Computer Operator/ Data Entry', 'Computer Operator/ Data Entry'),
    ('Instructional Designer', 'Instructional Designer'),
    ('EDP Analyst', 'EDP Analyst'),
    ('IT/ Networking (EDP) - Manager', 'IT/ Networking (EDP) - Manager'),
    ('Information Systems (MIS) - Manager', 'Information Systems (MIS) - Manager'),
    ('MIS Executive', 'MIS Executive'),
    ('VP/ Head - Technology (IT)', 'VP/ Head - Technology (IT)'),
    ('Chief Technology Officer', 'Chief Technology Officer'),
    ('Chief Information Officer', 'Chief Information Officer'),
    ('VP - Operations/ COO', 'VP - Operations/ COO'),
    ('SBU Head /Profit Centre Head', 'SBU Head /Profit Centre Head'),
    ('CEO/ MD/ Country Manager', 'CEO/ MD/ Country Manager'),
    ('Director on Board', 'Director on Board'),
    ('External Consultant', 'External Consultant'),
    ('Other Software/Hardware/EDP', 'Other Software/Hardware/EDP'),

    ('Fresher', 'Fresher'),
    ('Company Secretary', 'Company Secretary'),
    ('Lawyer/ Attorney', 'Lawyer/ Attorney'),
    ('Legal Advisor', 'Legal Advisor'),
    ('Legal Assistant/ Apprentcie', 'Legal Assistant/ Apprentcie'),
    ('Legal Consultant/ Solicitor', 'Legal Consultant/ Solicitor'),
    ('Law Officer', 'Law Officer'),
    ('Patent', 'Patent'),
    ('Private Practitioner / Lawyer', 'Private Practitioner / Lawyer'),
    ('Proof Reader (Law)', 'Proof Reader (Law)'),
    ('Legal Editor', 'Legal Editor'),
    ('Legal Services - Manager', 'Legal Services - Manager'),
    ('Legal Head', 'Legal Head'),
    ('Other Legal/ Law', 'Other Legal/ Law'),

    ('Fresher', 'Fresher'),
    ('Trainee/ Management Trainee', 'Trainee/ Management Trainee'),
    ('Telesales/ Telemarketing Executive', 'Telesales/ Telemarketing Executive'),
    ('Corp Communications - Manager/ Executive', 'Corp Communications - Manager/ Executive'),
    ('Head - Corp Communications', 'Head - Corp Communications'),
    ('Advertising - Executive', 'Advertising - Executive'),
    ('Advertising - Manager', 'Advertising - Manager'),
    ('Public Relations - Executive', 'Public Relations - Executive'),
    ('Public Relations - Manager', 'Public Relations - Manager'),
    ('Events/ Promotions Manager', 'Events/ Promotions Manager'),
    ('Manager / Head - Internet Marketing', 'Manager / Head - Internet Marketing'),
    ('Direct Marketing - Executive', 'Direct Marketing - Executive'),
    ('Direct Marketing - Manager', 'Direct Marketing - Manager'),
    ('Market Research - Executive', 'Market Research - Executive'),
    ('Market Research - Manager', 'Market Research - Manager'),
    ('Marketing Executive', 'Marketing Executive'),
    ('Marketing Manager', 'Marketing Manager'),
    ('Alliances Manager', 'Alliances Manager'),
    ('Business Analyst/ Consultant', 'Business Analyst/ Consultant'),
    ('Brand Manager', 'Brand Manager'),
    ('Product Executive', 'Product Executive'),
    ('Product Manager/ Product Head', 'Product Manager/ Product Head'),
    ('Marcom Executive', 'Marcom Executive'),
    ('Marcom - Manager / Head', 'Marcom - Manager / Head'),
    ('Executive - Internet Marketing', 'Executive - Internet Marketing'),
    ('Social Media Executive', 'Social Media Executive'),
    ('Head - Direct Marketing', 'Head - Direct Marketing'),
    ('Head - Public Relations', 'Head - Public Relations'),
    ('Head - Advertising', 'Head - Advertising'),
    ('VP/ GM/ Head - Marketing', 'VP/ GM/ Head - Marketing'),
    ('External Consultant', 'External Consultant'),
    ('Other Marketing', 'Other Marketing'),


    ('Fresher', 'Fresher'),
    ('Graduate Trainee/ Management Trainee', 'Graduate Trainee/ Management Trainee'),
    ('Computer Operator/ Data Entry', 'Computer Operator/ Data Entry'),
    ('Transit Centre (Rail) - Executive', 'Transit Centre (Rail) - Executive'),
    ('Distribution - Head', 'Distribution - Head'),
    ('Transportation/ Shipping Supervisor', 'Transportation/ Shipping Supervisor'),
    ('Logistics - Co-ordinator', 'Logistics - Co-ordinator'),
    ('Logistics - Head/ Mgr', 'Logistics - Head/ Mgr'),
    ('Purchase Officer/ Co-ordinator/ Executive', 'Purchase Officer/ Co-ordinator/ Executive'),
    ('Purchase Manager', 'Purchase Manager'),
    ('Purchase - Head', 'Purchase - Head'),
    ('Vendor Development Manager', 'Vendor Development Manager'),
    ('Inventory Control Manager/ Materials Manager', 'Inventory Control Manager/ Materials Manager'),
    ('Country Network Coordinator', 'Country Network Coordinator'),
    ('POD Management', 'POD Management'),
    ('Traffic Clerk', 'Traffic Clerk'),
    ('Fleet Supervisor', 'Fleet Supervisor'),
    ('Supply Chain - Head', 'Supply Chain - Head'),
    ('External Consultant', 'External Consultant'),
    ('Store Keeper/ Warehouse Assistant', 'Store Keeper/ Warehouse Assistant'),
    ('Commercial - Manager', 'Commercial - Manager'),
    ('Materials - Head/ GM', 'Materials - Head/ GM'),
    ('VP/ GM - Commercial', 'VP/ GM - Commercial'),
    ('VP Operations/ COO', 'VP Operations/ COO'),
    ('SBU Head /Profit Centre Head', 'SBU Head /Profit Centre Head'),
    ('CEO/ MD/ Country Manager', 'CEO/ MD/ Country Manager'),
    ('Director on Board', 'Director on Board'),
    ('External Consultant', 'External Consultant'),
    ('Other Purchase/ Supply Chain', 'Other Purchase/ Supply Chain'),

    ('Fresher', 'Fresher'),
    ('Sales Trainee/ Management Trainee', 'Sales Trainee/ Management Trainee'),
    ('Sales Exec/ Sales Representative', 'Sales Exec/ Sales Representative'),
    ('Medical Representative', 'Medical Representative'),
    ('Channel Sales Manager', 'Channel Sales Manager'),
    ('Relationship Mgr/ Account Servicing', 'Relationship Mgr/ Account Servicing'),
    ('Key Accounts Manager', 'Key Accounts Manager'),
    ('Institutional sales', 'Institutional sales'),
    ('Business Development Manager', 'Business Development Manager'),
    ('Business Development Executive', 'Business Development Executive'),
    ('Regional Sales Manager', 'Regional Sales Manager'),
    ('Area/ Territory Sales Manager', 'Area/ Territory Sales Manager'),
    ('Sales Promotion Manager', 'Sales Promotion Manager'),
    ('International Business Dev Mgr', 'International Business Dev Mgr'),
    ('Branch Manager', 'Branch Manager'),
    ('Merchandiser', 'Merchandiser'),
    ('Direct Sales Agent/ Commission Agent', 'Direct Sales Agent/ Commission Agent'),
    ('Telesales/ Telemarketing Executive', 'Telesales/ Telemarketing Executive'),
    ('Sales Trainer', 'Sales Trainer'),
    ('Presales Consultant', 'Presales Consultant'),
    ('Sales Engineer', 'Sales Engineer'),
    ('Sales Coordinator', 'Sales Coordinator'),
    ('Team Leader', 'Team Leader'),
    ('National Sales Manager', 'National Sales Manager'),
    ('VP/ GM/ Head - Sales', 'VP/ GM/ Head - Sales'),
    ('External Consultant', 'External Consultant'),
    ('Other Sales', 'Other Sales'),
    ('Corporate Sales', 'Corporate Sales'),

    ('Fresher', 'Fresher'),
    ('Graduate Trainee/ Management Trainee', 'Graduate Trainee/ Management Trainee'),
    ('Media Buying', 'Media Buying'),
    ('Media Planning', 'Media Planning'),
    ('Market Research', 'Market Research'),
    ('Editor/ Managing Editor', 'Editor/ Managing Editor'),
    ('Account Servicing', 'Account Servicing'),
    ('Correspondent/ Reporter', 'Correspondent/ Reporter'),
    ('Producer/ Production Manager', 'Producer/ Production Manager'),
    ('Instructional Designer', 'Instructional Designer'),
    ('TV Anchor', 'TV Anchor'),
    ('Art Director', 'Art Director'),
    ('Translator', 'Translator'),
    ('AV Executive/ Editor', 'AV Executive/ Editor'),
    ('Musician/Music Director', 'Musician/Music Director'),
    ('Graphic Designer/ Animator', 'Graphic Designer/ Animator'),
    ('Event Management', 'Event Management'),
    ('Content Writer', 'Content Writer'),
    ('Technical Writer', 'Technical Writer'),
    ('Copy Writer', 'Copy Writer'),
    ('Photographer', 'Photographer'),
    ('Cameraman', 'Cameraman'),
    ('Printing Technologist/ Manager', 'Printing Technologist/ Manager'),
    ('Studio Operations Manager', 'Studio Operations Manager'),
    ('Account Planning', 'Account Planning'),
    ('Choreographer', 'Choreographer'),
    ('Head - Lighting', 'Head - Lighting'),
    ('Sound Mixer / Engineer', 'Sound Mixer / Engineer'),
    ('VJ/RJ/DJ', 'VJ/RJ/DJ'),
    ('VP - Media Planning & Buying', 'VP - Media Planning & Buying'),
    ('Creative Director', 'Creative Director'),
    ('VP Client Servicing', 'VP Client Servicing'),
    ('Chief/ Deputy Chief of Bureau', 'Chief/ Deputy Chief of Bureau'),
    ('VP Operations/ COO', 'VP Operations/ COO'),
    ('SBU Head /Profit Centre Head', 'SBU Head /Profit Centre Head'),
    ('Proof Reader', 'Proof Reader'),
    ('CEO/ MD/ Country Manager', 'CEO/ MD/ Country Manager'),
    ('Director on Board', 'Director on Board'),
    ('External Consultant', 'External Consultant'),
    ('Other Media/ Journalism', 'Other Media/ Journalism'),

    ('Fresher', 'Fresher'),
    ('Graduate Trainee / Management Trainee', 'Graduate Trainee / Management Trainee'),
    ('Relationship manager', 'Relationship manager'),
    ('Actuary', 'Actuary'),
    ('Phone Banking Officer', 'Phone Banking Officer'),
    ('Consumer Banking Asset Operations', 'Consumer Banking Asset Operations'),
    ('Audit', 'Audit'),
    ('Bancassurance Executive/Manager', 'Bancassurance Executive/Manager'),
    ('M & A Advisor', 'M & A Advisor'),
    ('Cash Officer/ Manager', 'Cash Officer/ Manager'),
    ('Claims Management', 'Claims Management'),
    ('Clearing Officer/ Head', 'Clearing Officer/ Head'),
    ('Collections', 'Collections'),
    ('Compliance & Control', 'Compliance & Control'),
    ('Ratings Analyst', 'Ratings Analyst'),
    ('Derivatives Analyst', 'Derivatives Analyst'),
    ('Investment Banking', 'Investment Banking'),
    ('Trade Finance/ Cash Mgmt Services - Head/ Mgr', 'Trade Finance/ Cash Mgmt Services - Head/ Mgr'),
    ('Product Manager - Mutual Funds', 'Product Manager - Mutual Funds'),
    ('Product Manager - Cards', 'Product Manager - Cards'),
    ('Product Manager - Insurance', 'Product Manager - Insurance'),
    ('Product Manager - Auto/Home/Personal Loan', 'Product Manager - Auto/Home/Personal Loan'),
    ('Credit Research Analyst', 'Credit Research Analyst'),
    ('Hedge Fund Analyst/Trader', 'Hedge Fund Analyst/Trader'),
    ('Commodity Dealer', 'Commodity Dealer'),
    ('Equity Dealer', 'Equity Dealer'),
    ('Agency Manager', 'Agency Manager'),
    ('Private Banker', 'Private Banker'),
    ('Depository Participant', 'Depository Participant'),
    ('Project Finance - Head/ Mgr', 'Project Finance - Head/ Mgr'),
    ('Consumer Branch Banking Operations', 'Consumer Branch Banking Operations'),
    ('Consumer Banking Branch Head', 'Consumer Banking Branch Head'),
    ('Consumer Banking Region Head', 'Consumer Banking Region Head'),
    ('Corporate Banking Credit Analyst', 'Corporate Banking Credit Analyst'),
    ('Credit Head - Consumer Banking', 'Credit Head - Consumer Banking'),
    ('Corporate Banking Credit Control Manager', 'Corporate Banking Credit Control Manager'),
    ('Corporate Banking Branch Head', 'Corporate Banking Branch Head'),
    ('Corporate Banking Region Head', 'Corporate Banking Region Head'),
    ('Corporate Banking Customer Support Manager', 'Corporate Banking Customer Support Manager'),
    ('Corporate Banking Credit Head', 'Corporate Banking Credit Head'),
    ('Cash Management Operations', 'Cash Management Operations'),
    ('GM - Treasury', 'GM - Treasury'),
    ('Treasury Marketing Fixed Income', 'Treasury Marketing Fixed Income'),
    ('GM - Risks', 'GM - Risks'),
    ('Business Analyst', 'Business Analyst'),
    ('VP Operations/ COO', 'VP Operations/ COO'),
    ('Advisory', 'Advisory'),
    ('Chartered Accountant (CPA)', 'Chartered Accountant (CPA)'),
    ('Investment Advisor', 'Investment Advisor'),
    ('Portfolio Manager', 'Portfolio Manager'),
    ('Securities Analyst/ Stock Broker', 'Securities Analyst/ Stock Broker'),
    ('Economist', 'Economist'),
    ('Trading Advisor', 'Trading Advisor'),
    ('Underwriting', 'Underwriting'),
    ('Consumer Banking Head', 'Consumer Banking Head'),
    ('Corporate Banking Head', 'Corporate Banking Head'),
    ('SBU Head /Profit Centre Head', 'SBU Head /Profit Centre Head'),
    ('CEO/ MD/ Country Manager', 'CEO/ MD/ Country Manager'),
    ('Director on Board', 'Director on Board'),
    ('External Consultant', 'External Consultant'),
    ('Other Banking', 'Other Banking'),


    ('Fresher', 'Fresher'),
    ('Architect', 'Architect'),
    ('Civil Engineer', 'Civil Engineer'),
    ('Mechanical Engineer', 'Mechanical Engineer'),
    ('Design Engineer', 'Design Engineer'),
    ('HVAC engineering', 'HVAC engineering'),
    ('Electrical Engineer', 'Electrical Engineer'),
    ('Desalinational engineering', 'Desalinational engineering'),
    ('Duct engineers', 'Duct engineers'),
    ('Maintenance Engineer', 'Maintenance Engineer'),
    ('Contracting', 'Contracting'),
    ('Detailer', 'Detailer'),
    ('Civil Foreman', 'Civil Foreman'),
    ('Draftsman', 'Draftsman'),
    ('Quantity surveyor', 'Quantity surveyor'),
    ('Process Reporting manager', 'Process Reporting manager'),
    ('Project Manager', 'Project Manager'),
    ('Proposals & Estimation', 'Proposals & Estimation'),
    ('Surveyor', 'Surveyor'),
    ('Document Controller', 'Document Controller'),
    ('Marine engineering', 'Marine engineering'),
    ('MEP - Buyers', 'MEP - Buyers'),
    ('MEP - Surveyors', 'MEP - Surveyors'),
    ('Plumbing engineer', 'Plumbing engineer'),
    ('Power & Telecom engineering', 'Power & Telecom engineering'),
    ('Safety Officer', 'Safety Officer'),
    ('Planning Engineer', 'Planning Engineer'),
    ('Site engineer', 'Site engineer'),
    ('Scaffolding Sales Professionals', 'Scaffolding Sales Professionals'),
    ('Structural Designing', 'Structural Designing'),
    ('Water Treatment', 'Water Treatment'),
    ('Construction Suptd/ Inspector', 'Construction Suptd/ Inspector'),
    ('Director - Constructions', 'Director - Constructions'),
    ('Director - Architecture', 'Director - Architecture'),
    ('Director - Projects', 'Director - Projects'),
    ('VP/GM - Constructions', 'VP/GM - Constructions'),
    ('VP/GM - Architecture', 'VP/GM - Architecture'),
    ('VP/GM - Projects', 'VP/GM - Projects'),
    ('VP- Operations/ COO', 'VP- Operations/ COO'),
    ('SBU Head /Profit Centre Head', 'SBU Head /Profit Centre Head'),
    ('CEO/ MD/ Country Manager', 'CEO/ MD/ Country Manager'),
    ('Director on Board', 'Director on Board'),
    ('External Consultant', 'External Consultant'),
    ('Other Construction', 'Other Construction'),

    ('Librarian', 'Librarian'),
    ('Kindergarten/ Pre-primary Teacher', 'Kindergarten/ Pre-primary Teacher'),
    ('Language Teacher', 'Language Teacher'),
    ('Mathematics Teacher', 'Mathematics Teacher'),
    ('Science Teacher', 'Science Teacher'),
    ('Social Sciences Teacher', 'Social Sciences Teacher'),
    ('Music/ Dance Teacher', 'Music/ Dance Teacher'),
    ('IT Instructor', 'IT Instructor'),
    ('Laboratory Assistant', 'Laboratory Assistant'),
    ('Computer Teacher', 'Computer Teacher'),
    ('Trainer', 'Trainer'),
    ('School Coordinator', 'School Coordinator'),
    ('Principal/ Head of School', 'Principal/ Head of School'),
    ('Lecturer/ Professor', 'Lecturer/ Professor'),
    ('CEO/ MD', 'CEO/ MD'),
    ('Others', 'Others'),

    ('Trading', 'Trading'),
    ('Documentation/ Shipment Management', 'Documentation/ Shipment Management'),
    ('Liaison', 'Liaison'),
    ('International Business Dev Mgr', 'International Business Dev Mgr'),
    ('Merchandiser', 'Merchandiser'),
    ('VP - Operations/ COO', 'VP - Operations/ COO'),
    ('SBU Head /Profit Centre Head', 'SBU Head /Profit Centre Head'),
    ('CEO/MD/ Country Manager', 'CEO/MD/ Country Manager'),
    ('Director on Board', 'Director on Board'),
    ('External Consultant', 'External Consultant'),
    ('Other Export/ Import', 'Other Export/ Import'),


    ('Trainee / Intern', 'Trainee / Intern'),
    ('Doctor', 'Doctor'),
    ('Physician', 'Physician'),
    ('Dietician', 'Dietician'),
    ('Consultant', 'Consultant'),
    ('Pathologist', 'Pathologist'),
    ('Surgeon', 'Surgeon'),
    ('Orthopaedist', 'Orthopaedist'),
    ('Psychiatrist', 'Psychiatrist'),
    ('Specialist - Medicine', 'Specialist - Medicine'),
    ('Nephrologist', 'Nephrologist'),
    ('Physiotherapist', 'Physiotherapist'),
    ('Psycologist', 'Psycologist'),
    ('Occupational Therapist', 'Occupational Therapist'),
    ('Microbiologist', 'Microbiologist'),
    ('Chemist', 'Chemist'),
    ('Optometrist', 'Optometrist'),
    ('Radiologist', 'Radiologist'),
    ('Pharmacist', 'Pharmacist'),
    ('Perfusionist', 'Perfusionist'),
    ('Anaesthetist', 'Anaesthetist'),
    ('Ayurvedic Doctor', 'Ayurvedic Doctor'),
    ('Opthalmologist', 'Opthalmologist'),
    ('Nurse', 'Nurse'),
    ('Hearing Aid Technician', 'Hearing Aid Technician'),
    ('Lab Technician', 'Lab Technician'),
    ('Bio-chemist', 'Bio-chemist'),
    ('Radiographer', 'Radiographer'),
    ('ECG/ CGA Technician', 'ECG/ CGA Technician'),
    ('Operation Theater Technician', 'Operation Theater Technician'),
    ('Medical Officer', 'Medical Officer'),
    ('Front Office', 'Front Office'),
    ('Patient Service Associate', 'Patient Service Associate'),
    ('Medical Coder', 'Medical Coder'),
    ('House Keeping', 'House Keeping'),
    ('Cardiologist', 'Cardiologist'),
    ('Dentist', 'Dentist'),
    ('Dermatologist', 'Dermatologist'),
    ('ENT Specialist', 'ENT Specialist'),
    ('Gastronomist / Gastrologist', 'Gastronomist / Gastrologist'),
    ('Gyanecologist', 'Gyanecologist'),
    ('Medical Lab Supervisor', 'Medical Lab Supervisor'),
    ('Medical Superintendent/Dean/director', 'Medical Superintendent/Dean/director'),
    ('Neurologist', 'Neurologist'),
    ('Hepatologist', 'Hepatologist'),
    ('Oncologist', 'Oncologist'),
    ('Pediatrician', 'Pediatrician'),
    ('Pulmonologist', 'Pulmonologist'),
    ('Speech Language Pathologist/Therapist', 'Speech Language Pathologist/Therapist'),
    ('VP - Operations/ COO', 'VP - Operations/ COO'),
    ('SBU Head /Profit Centre Head', 'SBU Head /Profit Centre Head'),
    ('CEO/MD/ Country Manager', 'CEO/MD/ Country Manager'),
    ('Director on Board', 'Director on Board'),
    ('Other Health Care/ Hospitals', 'Other Health Care/ Hospitals'),

    ('Fresher', 'Fresher'),
    ('Trainee/ Management Trainee', 'Trainee/ Management Trainee'),
    ('Banquet Manager', 'Banquet Manager'),
    ('Bartender', 'Bartender'),
    ('Butler', 'Butler'),
    ('Chief Chef', 'Chief Chef'),
    ('F&B Manager', 'F&B Manager'),
    ('Lobby/ Duty Manager', 'Lobby/ Duty Manager'),
    ('Front Office Executive', 'Front Office Executive'),
    ('Front Office Manager', 'Front Office Manager'),
    ('Guest Relations Manager', 'Guest Relations Manager'),
    ('Banquet Sales', 'Banquet Sales'),
    ('Health Club Manager', 'Health Club Manager'),
    ('Hostess/ Host', 'Hostess/ Host'),
    ('Guest Relations Executive', 'Guest Relations Executive'),
    ('House Keeping - Head/ Manager', 'House Keeping - Head/ Manager'),
    ('Maintenance Technician', 'Maintenance Technician'),
    ('Reservation Manager', 'Reservation Manager'),
    ('Steward/ Waiter', 'Steward/ Waiter'),
    ('Restaurant Manager', 'Restaurant Manager'),
    ('Club Floor Manager', 'Club Floor Manager'),
    ('Business Center Manager', 'Business Center Manager'),
    ('House Keeping Executive', 'House Keeping Executive'),
    ('Room Service Manager', 'Room Service Manager'),
    ('Security Manager/ Officer', 'Security Manager/ Officer'),
    ('Laundry Manager', 'Laundry Manager'),
    ('Chef/ Kitchen Manager', 'Chef/ Kitchen Manager'),
    ('Sous Chef', 'Sous Chef'),
    ('Training Manager', 'Training Manager'),
    ('Travel Agent/ Tour Operator', 'Travel Agent/ Tour Operator'),
    ('Cashier', 'Cashier'),
    ('Concierge', 'Concierge'),
    ('Chief Engineer', 'Chief Engineer'),
    ('Shift Engineer/ Supervisor', 'Shift Engineer/ Supervisor'),
    ('Masseur', 'Masseur'),
    ('Attendant', 'Attendant'),
    ('Quality Assurance/ Control', 'Quality Assurance/ Control'),
    ('VP/ GM - Quality', 'VP/ GM - Quality'),
    ('VP Operations/ COO', 'VP Operations/ COO'),
    ('SBU Head /Profit Centre Head', 'SBU Head /Profit Centre Head'),
    ('CEO/ MD/ Country Manager', 'CEO/ MD/ Country Manager'),
    ('Director on Board', 'Director on Board'),
    ('GM/ DGM', 'GM/ DGM'),
    ('External Consultant', 'External Consultant'),
    ('Other Hotels/ Restaurants', 'Other Hotels/ Restaurants'),

    ('Fresher', 'Fresher'),
    ('Graduate Trainee / Management Trainee', 'Graduate Trainee / Management Trainee'),
    ('Chemical Engineer', 'Chemical Engineer'),
    ('Civil Engineer', 'Civil Engineer'),
    ('Design Manager/ Engineer', 'Design Manager/ Engineer'),
    ('Electrical Engineer', 'Electrical Engineer'),
    ('Electronics/ Instrumentation Engineer', 'Electronics/ Instrumentation Engineer'),
    ('Spares Manager/ Engineer', 'Spares Manager/ Engineer'),
    ('Environmental Engineer', 'Environmental Engineer'),
    ('Industrial Engineering', 'Industrial Engineering'),
    ('Mechanical Engineer', 'Mechanical Engineer'),
    ('Chief Engineer', 'Chief Engineer'),
    ('Maintenance', 'Maintenance'),
    ('Tool Room', 'Tool Room'),
    ('Paint Shop', 'Paint Shop'),
    ('Press Shop', 'Press Shop'),
    ('Weld Shop', 'Weld Shop'),
    ('Foreman', 'Foreman'),
    ('Draughtsman', 'Draughtsman'),
    ('Machine Operator', 'Machine Operator'),
    ('Assembler', 'Assembler'),
    ('Floor Supervisor', 'Floor Supervisor'),
    ('Workshop Manager', 'Workshop Manager'),
    ('Process Manager/ Engineer', 'Process Manager/ Engineer'),
    ('Production Manager/ Engineer', 'Production Manager/ Engineer'),
    ('Projects', 'Projects'),
    ('Tech/ Engg - Manager', 'Tech/ Engg - Manager'),
    ('Quality Assurance/ Control', 'Quality Assurance/ Control'),
    ('R & D Manager', 'R & D Manager'),
    ('Safety Officer/ Engineer', 'Safety Officer/ Engineer'),
    ('Service Manager/ Engineer', 'Service Manager/ Engineer'),
    ('Technician', 'Technician'),
    ('Marine Engineer', 'Marine Engineer'),
    ('Plant Head/ Factory Manager', 'Plant Head/ Factory Manager'),
    ('Mines Engineer', 'Mines Engineer'),
    ('Automotive Engineer', 'Automotive Engineer'),
    ('Aviation Engineer', 'Aviation Engineer'),
    ('Planning Engineer', 'Planning Engineer'),
    ('Sales Engineer', 'Sales Engineer'),
    ('Application Engineer', 'Application Engineer'),
    ('Textile Designer', 'Textile Designer'),
    ('Apparel Designer', 'Apparel Designer'),
    ('Accessory Designer', 'Accessory Designer'),
    ('Footwear Designer', 'Footwear Designer'),
    ('Jewelry Designer', 'Jewelry Designer'),
    ('Product Manager', 'Product Manager'),
    ('Packaging', 'Packaging'),
    ('Customer Service/ Tech Support', 'Customer Service/ Tech Support'),
    ('Lab Staff', 'Lab Staff'),
    ('Research Assistant', 'Research Assistant'),
    ('Data Management/ Statistics', 'Data Management/ Statistics'),
    ('Research Scientist', 'Research Scientist'),
    ('Technical Writer', 'Technical Writer'),
    ('Quality Assurance - Manager', 'Quality Assurance - Manager'),
    ('SBU Head/ Profit Centre Head', 'SBU Head/ Profit Centre Head'),
    ('VP/ GM - Engg/ Production', 'VP/ GM - Engg/ Production'),
    ('VP/ GM - Quality', 'VP/ GM - Quality'),
    ('VP/GM - R & D (Production & Engg)', 'VP/GM - R & D (Production & Engg)'),
    ('VP / GM - Design (Production & Engg)', 'VP / GM - Design (Production & Engg)'),
    ('External Consultant', 'External Consultant'),
    ('CEO/ MD/ Country Manager', 'CEO/ MD/ Country Manager'),
    ('VP Operations / COO', 'VP Operations / COO'),
    ('Director on Board', 'Director on Board'),
    ('Other Production/ Engineering/ R&D', 'Other Production/ Engineering/ R&D'),


    ('Fresher', 'Fresher'),
    ('Foreman', 'Foreman'),
    ('Draughtsman', 'Draughtsman'),
    ('Rigger', 'Rigger'),
    ('Fire & gas technician', 'Fire & gas technician'),
    ('HVAC expert', 'HVAC expert'),
    ('Desalination expert', 'Desalination expert'),
    ('Drilling expert', 'Drilling expert'),
    ('Gas turbine expert', 'Gas turbine expert'),
    ('Petrophysics / Geologist / Seismic Interpretation', 'Petrophysics / Geologist / Seismic Interpretation'),
    ('Thermal inspector', 'Thermal inspector'),
    ('Safety Engineer', 'Safety Engineer'),
    ('Structural Engineering', 'Structural Engineering'),
    ('Electrical and Instrumentation Engineering', 'Electrical and Instrumentation Engineering'),
    ('Rotating / Packaging / Static', 'Rotating / Packaging / Static'),
    ('Engineering - Materials & Corrosion', 'Engineering - Materials & Corrosion'),
    ('Engineering - Facilities/ Surface', 'Engineering - Facilities/ Surface'),
    ('Engineering - Heating and Thermal Equipment', 'Engineering - Heating and Thermal Equipment'),
    ('Engineering - Offshore Structures', 'Engineering - Offshore Structures'),
    ('Engineering - Pipelines', 'Engineering - Pipelines'),
    ('Engineering - Pressure Equipment', 'Engineering - Pressure Equipment'),
    ('Engineering - Reactor &Solids Processing', 'Engineering - Reactor &Solids Processing'),
    ('Engineering - Support', 'Engineering - Support'),
    ('Reservoir Engineering', 'Reservoir Engineering'),
    ('Well Engineering', 'Well Engineering'),
    ('Exploration and Production Engineering', 'Exploration and Production Engineering'),
    ('Piping Engineering', 'Piping Engineering'),
    ('Mechanical Engineering', 'Mechanical Engineering'),
    ('SURF Engineers', 'SURF Engineers'),
    ('Field Engineer', 'Field Engineer'),
    ('Inspection Engineer', 'Inspection Engineer'),
    ('Chemical Engineer', 'Chemical Engineer'),
    ('Tank Design Engineering', 'Tank Design Engineering'),
    ('Process Engineering', 'Process Engineering'),
    ('Project Engineering', 'Project Engineering'),
    ('Production & Manufacturing Downstream', 'Production & Manufacturing Downstream'),
    ('QA / QC', 'QA / QC'),
    ('FPSO / FSO Conversion Engineer', 'FPSO / FSO Conversion Engineer'),
    ('Process Maintenance Engineer', 'Process Maintenance Engineer'),
    ('Risk Assessment Engineer', 'Risk Assessment Engineer'),
    ('Reliability Engineer', 'Reliability Engineer'),
    ('Subsea - Project', 'Subsea - Project'),
    ('Research &Technology Development', 'Research &Technology Development'),
    ('HSE Management Specialist', 'HSE Management Specialist'),
    ('HSEQ', 'HSEQ'),
    ('Gas Commercial Negotiator', 'Gas Commercial Negotiator'),
    ('Gas Regulators/Planners', 'Gas Regulators/Planners'),
    ('Oil Trader / Bunker Trader', 'Oil Trader / Bunker Trader'),
    ('Proposal & Estimation', 'Proposal & Estimation'),
    ('Commissioning', 'Commissioning'),
    ('Documentation Controller', 'Documentation Controller'),
    ('Packaging and Product Development', 'Packaging and Product Development'),
    ('Lab Technician', 'Lab Technician'),
    ('Surveyor', 'Surveyor'),
    ('EPC (Engineering, Procurement and Construction', 'EPC (Engineering, Procurement and Construction'),
    ('Refinery Manager / Project Manager', 'Refinery Manager / Project Manager'),
    ('Plant Supervisor', 'Plant Supervisor'),
    ('Head - Drilling & Completions', 'Head - Drilling & Completions'),
    ('Head - Development & Projects', 'Head - Development & Projects'),
    ('Head - EPC', 'Head - EPC'),
    ('SBU Head /Profit Centre Head', 'SBU Head /Profit Centre Head'),
    ('VP/GM - Projects', 'VP/GM - Projects'),
    ('VP-Operations / COO', 'VP-Operations / COO'),
    ('VP/GM - Manufacturing Plant', 'VP/GM - Manufacturing Plant'),
    ('VP/GM - Constructions', 'VP/GM - Constructions'),
    ('CEO/MD/ Country Manager', 'CEO/MD/ Country Manager'),
    ('Director on Board', 'Director on Board'),
    ('External Consultant', 'External Consultant'),
    ('Other Oil & Gas', 'Other Oil & Gas'),
    ('Subsea - Installation / System and Controls', 'Subsea - Installation / System and Controls'),
    ('Subsea - Pipeline / Flow Assurance', 'Subsea - Pipeline / Flow Assurance'),

    ('Fresher', 'Fresher'),
    ('Practical Training/Internship', 'Practical Training/Internship'),
    ('Chemist', 'Chemist'),
    ('Postdoc Position/Fellowship', 'Postdoc Position/Fellowship'),
    ('Lab Staff', 'Lab Staff'),
    ('Microbiologist', 'Microbiologist'),
    ('Product Manager', 'Product Manager'),
    ('Nutritionist', 'Nutritionist'),
    ('Pharmacist', 'Pharmacist'),
    ('Quality Assurance - Manager', 'Quality Assurance - Manager'),
    ('Basic Research Scientist', 'Basic Research Scientist'),
    ('VP Operations/ COO', 'VP Operations/ COO'),
    ('VP/ GM - Quality', 'VP/ GM - Quality'),
    ('VP/ GM R&D (Pharma)', 'VP/ GM R&D (Pharma)'),
    ('Bio-Technology Research Scientist', 'Bio-Technology Research Scientist'),
    ('Clinical Research Scientist', 'Clinical Research Scientist'),
    ('Chemical Research Scientist', 'Chemical Research Scientist'),
    ('Drug Regulatory Doctor', 'Drug Regulatory Doctor'),
    ('Regulatory Executive', 'Regulatory Executive'),
    ('Pharmaceutical Research Scientist', 'Pharmaceutical Research Scientist'),
    ('Analytical Chemistry Scientist', 'Analytical Chemistry Scientist'),
    ('Goods Manufacturing Practices (GMP)', 'Goods Manufacturing Practices (GMP)'),
    ('Data Management/ Statistics', 'Data Management/ Statistics'),
    ('Documentation/ Medical Writing', 'Documentation/ Medical Writing'),
    ('Technology Transfer Engineer', 'Technology Transfer Engineer'),
    ('Quality Assurance/ Control', 'Quality Assurance/ Control'),
    ('Production Manager', 'Production Manager'),
    ('Medical Affairs Manager', 'Medical Affairs Manager'),
    ('Molecular Biologist', 'Molecular Biologist'),
    ('Nuclear Medicine', 'Nuclear Medicine'),
    ('Toxicologist', 'Toxicologist'),
    ('Formulation Scientist', 'Formulation Scientist'),
    ('SBU Head /Profit Centre Head', 'SBU Head /Profit Centre Head'),
    ('CEO/ MD/ Country Manager', 'CEO/ MD/ Country Manager'),
    ('Director on Board', 'Director on Board'),
    ('External Consultant', 'External Consultant'),
    ('Other Pharma', 'Other Pharma'),

    ('Fresher', 'Fresher'),
    ('Data Analyst', 'Data Analyst'),
    ('Web Analyst', 'Web Analyst'),
    ('Financial Analyst', 'Financial Analyst'),
    ('Business analyst', 'Business analyst'),
    ('Marketing Analyst', 'Marketing Analyst'),
    ('Insurance Analyst', 'Insurance Analyst'),
    ('Chief Information Officer', 'Chief Information Officer'),
    ('VP Operations / COO', 'VP Operations / COO'),
    ('CEO/ MD/ Country Manager', 'CEO/ MD/ Country Manager'),
    ('Director on Board', 'Director on Board'),
    ('External Consultant', 'External Consultant'),
    ('Other Analytics/Business Intelligence', 'Other Analytics/Business Intelligence'),


    ('Fresher', 'Fresher'),
    ('Management Trainee', 'Management Trainee'),
    ('Architect', 'Architect'),
    ('Interior Designer', 'Interior Designer'),
    ('Brokerage', 'Brokerage'),
    ('Land Development', 'Land Development'),
    ('Property Management', 'Property Management'),
    ('Real Estate Appraising', 'Real Estate Appraising'),
    ('Real Estate Counseling', 'Real Estate Counseling'),
    ('Real Estate Research', 'Real Estate Research'),
    ('VP Operations/ COO', 'VP Operations/ COO'),
    ('SBU Head/ Profit Centre Head', 'SBU Head/ Profit Centre Head'),
    ('CEO/ MD/ Country Manager', 'CEO/ MD/ Country Manager'),
    ('Other Real Estate', 'Other Real Estate'),

    ('Fresher', 'Fresher'),
    ('Trainee/ Management Trainee', 'Trainee/ Management Trainee'),
    ('Area Manager', 'Area Manager'),
    ('Regional Manager', 'Regional Manager'),
    ('Shift Manager', 'Shift Manager'),
    ('Buyer / Sourcing Manager', 'Buyer / Sourcing Manager'),
    ('Front Desk', 'Front Desk'),
    ('Quality Assurance/ Control', 'Quality Assurance/ Control'),
    ('Retail Store Manager', 'Retail Store Manager'),
    ('Operations Executive/Supervisor', 'Operations Executive/Supervisor'),
    ('Merchandiser', 'Merchandiser'),
    ('Inventory Control Manager', 'Inventory Control Manager'),
    ('Cashier', 'Cashier'),
    ('Loyalty Program', 'Loyalty Program'),
    ('Sales Exec/ Sales Representative', 'Sales Exec/ Sales Representative'),
    ('Visual Merchandiser', 'Visual Merchandiser'),
    ('Loss Prevention Manager', 'Loss Prevention Manager'),
    ('Technical - Manager', 'Technical - Manager'),
    ('VP/ GM - Quality', 'VP/ GM - Quality'),
    ('GM', 'GM'),
    ('SBU Head /Profit Centre Head', 'SBU Head /Profit Centre Head'),
    ('VP Operations/ COO', 'VP Operations/ COO'),
    ('CEO/ MD/ Country Manager', 'CEO/ MD/ Country Manager'),
    ('Director on Board', 'Director on Board'),
    ('External Consultant', 'External Consultant'),
    ('Other Retail Chains/Shops', 'Other Retail Chains/Shops'),


    ('Fresher', 'Fresher'),
    ('Graduate Trainee / Management Trainee', 'Graduate Trainee / Management Trainee'),
    ('RF Planning Engineer', 'RF Planning Engineer'),
    ('Network Installation & Administration', 'Network Installation & Administration'),
    ('Network Administrator', 'Network Administrator'),
    ('Network Planning - Chief Engineer', 'Network Planning - Chief Engineer'),
    ('GSM Engineer', 'GSM Engineer'),
    ('Telecom Engineer', 'Telecom Engineer'),
    ('RF Installation & Administration Engineer', 'RF Installation & Administration Engineer'),
    ('RF Planning - Chief Engineer', 'RF Planning - Chief Engineer'),
    ('O&M Engineer', 'O&M Engineer'),
    ('Switching - Engineer', 'Switching - Engineer'),
    ('Switching - Chief Engineer', 'Switching - Chief Engineer'),
    ('System Administrator', 'System Administrator'),
    ('System Engineer', 'System Engineer'),
    ('System Security - Engineer', 'System Security - Engineer'),
    ('System Security - Chief Engineer', 'System Security - Chief Engineer'),
    ('Network Planning - Engineer', 'Network Planning - Engineer'),
    ('Customer Support Engineer/ Technician', 'Customer Support Engineer/ Technician'),
    ('Outside Service Providers', 'Outside Service Providers'),
    ('Regional Mgr/ Manager(Operations)', 'Regional Mgr/ Manager(Operations)'),
    ('Quality Assurance Executive', 'Quality Assurance Executive'),
    ('Quality Assurance - Manager', 'Quality Assurance - Manager'),
    ('Project Manager', 'Project Manager'),
    ('VP/ GM - Quality', 'VP/ GM - Quality'),
    ('VP/ Head - Technology (Telecom/ ISP)', 'VP/ Head - Technology (Telecom/ ISP)'),
    ('VP Operations/ COO', 'VP Operations/ COO'),
    ('SBU Head /Profit Centre Head', 'SBU Head /Profit Centre Head'),
    ('CEO/ MD/ Country Manager', 'CEO/ MD/ Country Manager'),
    ('Director on Board', 'Director on Board'),
    ('External Consultant', 'External Consultant'),
    ('Other Telecom/ISP', 'Other Telecom/ISP'),


    ('Fresher', 'Fresher'),
    ('Trainee/ Management Trainee', 'Trainee/ Management Trainee'),
    ('Reservation and Ticketing', 'Reservation and Ticketing'),
    ('Domestic Travel', 'Domestic Travel'),
    ('International Travel', 'International Travel'),
    ('Documentaion & VISA', 'Documentaion & VISA'),
    ('Travel Agent/ Tour Operator', 'Travel Agent/ Tour Operator'),
    ('Air Hostess/ Steward/ Cabin Crew', 'Air Hostess/ Steward/ Cabin Crew'),
    ('Pilot', 'Pilot'),
    ('Ground Staff', 'Ground Staff'),
    ('Maintenance Engineer', 'Maintenance Engineer'),
    ('Cashier', 'Cashier'),
    ('Office Assistant', 'Office Assistant'),
    ('Branch Head', 'Branch Head'),
    ('VP - Operations/ COO', 'VP - Operations/ COO'),
    ('SBU Head /Profit Centre Head', 'SBU Head /Profit Centre Head'),
    ('CEO/MD/ Country Manager', 'CEO/MD/ Country Manager'),
    ('Director on Board', 'Director on Board'),
    ('GM', 'GM'),
    ('External Consultant', 'External Consultant'),
    ('Other Travel/ Airlines', 'Other Travel/ Airlines'),

    ('Entrepreneur', 'Entrepreneur'),
    ('Fashion Designer',  'Fashion Designer'),
    ('Fitness Trainer',  'Fitness Trainer'),
    ('Horticulturist',  'Horticulturist'),
    ('Model',  'Model'),
    ('Painter',  'Painter'),
    ('Security Officer',  'Security Officer'),
    ('Statistician',  'Statistician'),
    ('Consultant',  'Consultant'),
    ('Electrician',  'Electrician'),
    ('Driver/Chauffeur',  'Driver/Chauffeur'),
    ('Beautician',  'Beautician'),
    ('Language Expert',  'Language Expert'),
    ('AC Technician',  'AC Technician'),
    ('Jewellery Designer',  'Jewellery Designer'),
    ('Other Roles',  'Other Roles'),
)

MASTERS_EDU = (  
    ('Chartered Accountant', 'Chartered Accountant'),
    ('CA Inter', 'CA Inter'),
    ('Chartered Financial Analyst', 'Chartered Financial Analyst'),
    ('Company Secretary', 'Company Secretary'),
    ('Doctor of Medicine (MD)', 'Doctor of Medicine (MD)'),
    ('Doctor of Surgery (MS)', 'Doctor of Surgery (MS)'),
    ('Inst. of Cost & Works Accountants', 'Inst. of Cost & Works Accountants'),
    ('ICWA Inter', 'ICWA Inter'),
    ('Master of Architecture', 'Master of Architecture'),
    ('Master of Arts', 'Master of Arts'),
    ('Master of Commerce', 'Master of Commerce'),
    ('Master of Education', 'Master of Education'),
    ('Master of Laws (LLM)', 'Master of Laws (LLM)'),
    ('Master of Pharmacy', 'Master of Pharmacy'),
    ('Master of Technology/Engineering', 'Master of Technology/Engineering'),
    ('Master of Vetirenary Science', 'Master of Vetirenary Science'),
    ('Master of Computer Application', 'Master of Computer Application'),
    ('MBA/PG Diploma in Business Mgmt ', 'MBA/PG Diploma in Business Mgmt '),
    ('Other', 'Other'),

)
MASTERS_SPEC =(
    ('General (College Proprietary)','General (College Proprietary)'),
    ('Academic / General','Academic / General'),
    ('Commercial','Commercial'),
    ('Technical','Technical'),
    ('Vocational','Vocational'),
    ('Religion','Religion'),
    ('Aircraft Maintenance','Aircraft Maintenance'),
    ('Autoclave Operation','Autoclave Operation'),
    ('Cement Technology','Cement Technology'),
    ('Chemical','Chemical'),
    ('Civil','Civil'),
    ('Computers ','Computers '),
    ('Drilling & Exploration Technology','Drilling & Exploration Technology'),
    ('Electrical','Electrical'),
    ('Electronics','Electronics'),
    ('Engineering','Engineering'),
    ('Export/Import','Export/Import'),
    ('Fashion Designing/Other Designing','Fashion Designing/Other Designing'),
    ('Foundry & Forging','Foundry & Forging'),
    ('Graphic/ Web Designing','Graphic/ Web Designing'),
    ('Hotel Management','Hotel Management'),
    ('Instrumentation & Control','Instrumentation & Control'),
    ('Insurance','Insurance'),
    ('Jewelery Design & Manufacturing','Jewelery Design & Manufacturing'),
    ('Machine Tool Maintenance & Repair','Machine Tool Maintenance & Repair'),
    ('Management','Management'),
    ('Mechanical','Mechanical'),
    ('Medical Instrumentation','Medical Instrumentation'),
    ('Medical Lab Technology','Medical Lab Technology'),
    ('Petrochemical Technology','Petrochemical Technology'),
    ('Process Instrumentation','Process Instrumentation'),
    ('Production Technology','Production Technology'),
    ('Refinery & Petro Chemical Technology','Refinery & Petro Chemical Technology'),
    ('Refrigeration & Airconditioning','Refrigeration & Airconditioning'),
    ('Surface Coating Technology','Surface Coating Technology'),
    ('Survey Engineering','Survey Engineering'),
    ('Telecommunication','Telecommunication'),
    ('Tool & Die Technology','Tool & Die Technology'),
    ('Tourism','Tourism'),
    ('Videography','Videography'),
    ('Visual Arts','Visual Arts'),
    ('Vocational Course','Vocational Course'),
    ('Welding Technology','Welding Technology'),
    ('Architecture','Architecture'),
    ('Arabic','Arabic'),
    ('Arts&Humanities','Arts&Humanities'),
    ('Communication','Communication'),
    ('Economics','Economics'),
    ('English','English'),
    ('Film','Film'),
    ('Fine arts','Fine arts'),
    ('Hindi','Hindi'),
    ('History','History'),
    ('Journalism','Journalism'),
    ('Middle Eastern Studies','Middle Eastern Studies'),
    ('Political Science','Political Science'),
    ('PR/Advertising','PR/Advertising'),
    ('Psychology','Psychology'),
    ('Religion','Religion'),
    ('Sociology','Sociology'),
    ('Statistics','Statistics'),
    ('Urdu','Urdu'),
    ('Management','Management'),
    ('Commerce','Commerce'),
    ('Dentistry','Dentistry'),
    ('Education','Education'),
    ('Religious Education','Religious Education'),
    ('Law','Law'),
    ('Pharmacy','Pharmacy'),
    ('Agriculture','Agriculture'),
    ('Anthropology','Anthropology'),
    ('Bio-Chemistry','Bio-Chemistry'),
    ('Biology','Biology'),
    ('Botany','Botany'),
    ('Chemistry','Chemistry'),
    ('Dairy','Dairy'),
    ('Technology','Technology'),
    ('Environmental science',''),
    ('Food Technology','Food Technology'),
    ('Geology','Geology'),
    ('Home Science','Home Science'),
    ('Maths','Maths'),
    ('Microbiology','Microbiology'),
    ('Nursing','Nursing'),
    ('Physics','Physics'),
    ('Statistics','Statistics'),
    ('Zoology','Zoology'),
    ('General','General'),
    ('Agriculture','Agriculture'),
    ('Automobile','Automobile'),
    ('Aviation','Aviation'),
    ('Bio-Technology','Bio-Technology'),
    ('Biomedical','Biomedical'),
    ('Ceramics','Ceramics'),
    ('Chemical','Chemical'),
    ('Civil','Civil'),
    ('Electronics/Telecomunication','Electronics/Telecomunication'),
    ('Energy','Energy'),
    ('Environmental','Environmental'),
    ('Instrumentation','Instrumentation'),
    ('Marine','Marine'),
    ('Mechanical','Mechanical'),
    ('Metallurgy','Metallurgy'),
    ('Mineral','Mineral'),
    ('Mining','Mining'),
    ('Nuclear','Nuclear'),
    ('Paint/Oil','Paint/Oil'),
    ('Petroleum','Petroleum'),
    ('Plastics','Plastics'),
    ('Production/Industrial','Production/Industrial'),
    ('Textile','Textile'),
    ('Other Engineering','Other Engineering'),
    ('Veterinary Sciences','Veterinary Sciences'),
    ('Medicine','Medicine'),
    ('Chartered Accountant','Chartered Accountant'),
    ('Finance','Finance'),
    ('Company Secretary','Company Secretary'),
    ('Anatomy','Anatomy'),
    ('Anesthesiology','Anesthesiology'),
    ('Aviation Medicine','Aviation Medicine'),
    ('Biochemistry','Biochemistry'),
    ('Bio-Physics','Bio-Physics'),
    ('Blood Banking & Immuno. Haem','Blood Banking & Immuno. Haem'),
    ('Critical Care Medicine','Critical Care Medicine'),
    ('Community Health Administration','Community Health Administration'),
    ('Community Medicine','Community Medicine'),
    ('Dermatology','Dermatology'),
    ('Forensic Medicine','Forensic Medicine'),
    ('General Medicine','General Medicine'),
    ('Geriatrics','Geriatrics'),
    ('Gynecology','Gynecology'),
    ('Health Administration','Health Administration'),
    ('Hospital Administration','Hospital Administration'),
    ('Lab Medicine','Lab Medicine'),
    ('Leprosy','Leprosy'),
    ('Maternity & Child Health','Maternity & Child Health'),
    ('Microbiology','Microbiology'),
    ('Nuclear Medicine','Nuclear Medicine'),
    ('Obstetrics','Obstetrics'),
    ('Ophthalmology','Ophthalmology'),
    ('Pathology','Pathology'),
    ('Pediatrics','Pediatrics'),
    ('Pharmacology','Pharmacology'),
    ('Physical Medicine & Rehabilitation','Physical Medicine & Rehabilitation'),
    ('Physiology','Physiology'),
    ('Psychiatry','Psychiatry'),
    ('Pulmonary Medicine','Pulmonary Medicine'),
    ('R & D','R & D'),
    ('Radio Diagnosis','Radio Diagnosis'),
    ('Radio Therapy','Radio Therapy'),
    ('Radiology','Radiology'),
    ('Social and Preventive Medicine','Social and Preventive Medicine'),
    ('Tropical Medicine','Tropical Medicine'),
    ('Tuberculosis & Chest Diseases','Tuberculosis & Chest Diseases'),
    ('Veneriology','Veneriology'),
    ('Anaesthesia','Anaesthesia'),
    ('Cardiology','Cardiology'),
    ('Dermatology','Dermatology'),
    ('ENT','ENT'),
    ('General Surgery','General Surgery'),
    ('Gyneocology','Gyneocology'),
    ('Hepatology','Hepatology'),
    ('Immunology Microbiology','Immunology Microbiology'),
    ('Neonatal','Neonatal'),
    ('Nephrology/Urology','Nephrology/Urology'),
    ('Obstretrics','Obstretrics'),
    ('Oncology','Oncology'),
    ('Opthalmology','Opthalmology'),
    ('Orthopedic','Orthopedic'),
    ('Pathology','Pathology'),
    ('Pediatrics','Pediatrics'),
    ('Psychiatry/Psychology','Psychiatry/Psychology'),
    ('Rheumatology','Rheumatology'),
    ('Cost & Works Accountant','Cost & Works Accountant'),
    ('Advertising/Mass Communication','Advertising/Mass Communication'),
    ('Finance','Finance'),
    ('HR/Industrial Relations','HR/Industrial Relations'),
    ('Information Technology','Information Technology'),
    ('International Business','International Business'),
    ('Marketing','Marketing'),
    ('Systems','Systems'),
    ('Other','Other'),
    )

EDUCATION_REQUIRED = (
    ('Diploma', 'Diploma'),   
    ('Intermediate Schooling', 'Intermediate Schooling'),
    ('Secondary Schooling', 'Secondary Schooling'),
    ('Degree - Any', 'Degree - Any'),
    ('PG - Any', 'PG - Any'),
    ('Bachelor of Architecture', 'Bachelor of Architecture'),
    ('Bachelor of Arts', 'Bachelor of Arts'),
    ('Bachelor of Business Administration', 'Bachelor of Business Administration'),
    ('Bachelor of Commerce', 'Bachelor of Commerce'),
    ('Bachelor of Dental Sugery', 'Bachelor of Dental Sugery'),
    ('Bachelor of Education', 'Bachelor of Education'),
    ('Bachelor of Hotel Management', 'Bachelor of Hotel Management'),
    ('Bachelor of Laws (LLB)', 'Bachelor of Laws (LLB)'),
    ('Bachelor of Pharmacy', 'Bachelor of Pharmacy'),
    ('Bachelor of Science', 'Bachelor of Science'),
    ('Bachelor of Technology/Engineering', 'Bachelor of Technology/Engineering'),
    ('Bachelor of Vetirenary Science', 'Bachelor of Vetirenary Science'),
    ('Bachelor of Computer Application', 'Bachelor of Computer Application'),
    ('MBBS', 'MBBS'),
    ('Chartered Accountant', 'Chartered Accountant'),
    ('CA Inter', 'CA Inter'),
    ('Chartered Financial Analyst', 'Chartered Financial Analyst'),
    ('Company Secretary', 'Company Secretary'),
    ('Doctor of Medicine (MD)', 'Doctor of Medicine (MD)'),
    ('Doctor of Surgery (MS)', 'Doctor of Surgery (MS)'),
    ('Inst. of Cost & Works Accountants', 'Inst. of Cost & Works Accountants'),
    ('ICWA Inter', 'ICWA Inter'),
    ('Master of Architecture', 'Master of Architecture'),
    ('Master of Arts', 'Master of Arts'),
    ('Master of Commerce', 'Master of Commerce'),
    ('Master of Education', 'Master of Education'),
    ('Master of Laws (LLM)', 'Master of Laws (LLM)'),
    ('Master of Pharmacy', 'Master of Pharmacy'),
    ('Master of Technology/Engineering', 'Master of Technology/Engineering'),
    ('Master of Vetirenary Science', 'Master of Vetirenary Science'),
    ('Master of Computer Application', 'Master of Computer Application'),
    ('MBA/PG Diploma in Business Mgmt ', 'MBA/PG Diploma in Business Mgmt '),
    ('Other', 'Other'),

)

COUNTRY_CODE = (
    ('93', '93'),
    ('355', '355'),
    ('213', '213'),
    ('1684','1684'),
    ('376', '376'),
    ('244', '244'),
    ('672','672'),
    ('1268', '1268'),
    ('54', '54'),
    ('374', '374'),
    ('297', '297'),
    ('61', '61'),
    ('43', '43'),
    ('994', '994'),
    ('1242', '1242'),
    ('973', '973'),
    ('880', '880'),
    ('1246', '1246'),
    ('375', '375'),
    ('32', '32'),
    ('501', '501'),
    ('229', '229'),
    ('975', '975'),
    ('591', '591'),
    ('387', '387'),
    ('267', '267'),
    ('61', '61'),
    ('55', '55'),
    ('672', '672'),
    ('359', '359'),
    ('226', '226'),
    ('257', '257'),
    ('855', '855'),
    ('237', '237'),
    ('1', '1'),
    ('238', '238'),
    ('236', '236'),
    ('235', '235'),
    ('56', '56'),
    ('86', '86'),
    ('57', '57'),
    ('95', '95'),
    ('269', '269'),
    ('243', '243'),
    ('242', '242'),
    ('506', '506'),
    ('225', '225'),
    ('385', '385'),
    ('53', '53'),
    ('850', '850'),
    ('82', '82'),
    ('970', '970'),
    ('357', '357'),
    ('420', '420'),
    ('45', '45'),
    ('253', '253'),
    ('1767', '1767'),
    ('1809', '1809'),
    ('593', '593'),
    ('20', '20'),
    ('503', '503'),
    ('240', '240'),
    ('291', '291'),
    ('372', '372'),
    ('251', '251'),
    ('679', '679'),
    ('358', '358'),
    ('33', '33'),
    ('262', '262'),
    ('241', '241'),
    ('220', '220'),
    ('995', '995'),
    ('49', '49'),
    ('233', '233'),
    ('30', '30'),
    ('1473', '1473'),
    ('502', '502'),
    ('224', '224'),
    ('245', '245'),
    ('592', '592'),
    ('509', '509'),
    ('379', '379'),
    ('504', '504'),
    ('852', '852'),
    ('36', '36'),
    ('354', '354'),
    ('91', '91'),
    ('62', '62'),
    ('98', '98'),
    ('964', '964'),
    ('353', '353'),
    ('972', '972'),
    ('39', '39'),
    ('1876', '1876'),
    ('81', '81'),
    ('962', '962'),
    ('7', '7'),
    ('254', '254'),
    ('686', '686'),
    ('965', '965'),
    ('996', '996'),
    ('856', '856'),
    ('371', '371'),
    ('961', '961'),
    ('266', '266'),
    ('231', '231'),
    ('218', '218'),
    ('423', '423'),
    ('370', '370'),
    ('352', '352'),
    ('853', '853'),
    ('389', '389'),
    ('261', '261'),
    ('265', '265'),
    ('60', '60'),
    ('960', '960'),
    ('223', '223'),
    ('356', '356'),
    ('692', '692'),
    ('222', '222'),
    ('230', '230'),
    ('52', '52'),
    ('691', '691'),
    ('373', '373'),
    ('377', '377'),
    ('976', '976'),
    ('212', '212'),
    ('258', '258'),
    ('264', '264'),
    ('674', '674'),
    ('977', '977'),
    ('31', '31'),
    ('599', '599'),
    ('64', '64'),
    ('505', '505'),
    ('227', '227'),
    ('234', '234'),
    ('47', '47'),
    ('968', '968'),
    ('92', '92'),
    ('680', '680'),
    ('507', '507'),
    ('675', '675'),
    ('595', '595'),
    ('51', '51'),
    ('63', '63'),
    ('48', '48'),
    ('351', '351'),
    ('974', '974'),
    ('262', '262'),
    ('40', '40'),
    ('7', '7'),
    ('250', '250'),
    ('1869', '1869'),
    ('1758', '1758'),
    ('1784', '1784'),
    ('685', '685'),
    ('378', '378'),
    ('239', '239'),
    ('966', '966'),
    ('221', '221'),
    ('381', '381'),
    ('248', '248'),
    ('232', '232'),
    ('65', '65'),
    ('421', '421'),
    ('386', '386'),
    ('677', '677'),
    ('252', '252'),
    ('27', '27'),
    ('34', '34'),
    ('94', '94'),
    ('249', '249'),
    ('597', '597'),
    ('47', '47'),
    ('268', '268'),
    ('46', '46'),
    ('41', '41'),
    ('963', '963'),
    ('886', '886'),
    ('992', '992'),
    ('255', '255'),
    ('66', '66'),
    ('228', '228'),
    ('676', '676'),
    ('1868', '1868'),
    ('216', '216'),
    ('90', '90'),
    ('993', '993'),
    ('688', '688'),
    ('256', '256'),
    ('380', '380'),
    ('971', '971'),
    ('44', '44'),
    ('1', '1'),
    ('598', '598'),
    ('998', '998'),
    ('678', '678'),
    ('58', '58'),
    ('84', '84'),
    ('212', '212'),
    ('967', '967'),
    ('260', '260'),
    ('263', '263'),
)


class Job(models.Model):
    from employer.models import CompanyProfile
    User._meta.get_field("username").max_length = 100
    recruiter = models.ForeignKey(User)
    company = models.ForeignKey(CompanyProfile, null=True, blank=True)
    job_title = models.CharField('Job Title', max_length=200)
    salary = models.CharField('Salary', null=True, blank=True, max_length=200)
    ref_code = models.CharField('Ref Code', max_length=15, null=True, blank=True)
    summary = models.CharField('Summary', max_length=2000)
    document = models.FileField (upload_to = "uploads/doc/", null=True, blank=True)
    skills = models.CharField('Skills Required', null=True, blank=True, max_length=200)
    order = models.IntegerField('Order', default=0)
    industry = models.CharField('Industry', max_length=70, choices=INDUSTRY)
    job_location = models.CharField('Job Location', max_length=200, choices=COUNTRY_CHOICES)
    function = models.CharField('Function', max_length=70, choices=FUNCTIONS)
    func_role = models.CharField('Function Role', max_length=70, choices=FUNC_ROLE, null=True, blank=True)
    education_req = models.CharField('Education Required', max_length=70, choices=EDUCATION_REQUIRED)
    specialization = models.CharField('Specialization', max_length=70, null=True, blank=True)
    nationality = models.CharField('Nationality', max_length=70, null=True, blank=True, choices=NATIONALITY)
    name = models.CharField('Name', max_length=200)
    phone = models.CharField('Phone', max_length=200,null=True, blank=True)
    mail_id = models.CharField('Email Id', max_length=70)
    posting_date = models.DateField('Posting Date', null=True, blank=True, auto_now_add=True)
    last_date = models.DateField('Last Date', null=True, blank=True)
    exp_req_min = models.IntegerField('Experience Required Min', null=True, blank=True, choices=YEARS)
    exp_req_max = models.IntegerField('Experience Required Max', null=True, blank=True, choices=YEARS)
    is_featured = models.BooleanField('Is Featured', default=False)
    description = models.TextField('Description', null=True, blank=True)
    is_publish = models.BooleanField('Publish', default=False)
    currency = models.CharField('Currency', max_length=30, null=True, blank=True, choices=CURRENCY)
    search_count = models.IntegerField('Search Count',null=True,blank=True,default=0)
    applicants_count = models.IntegerField('Applicant Count',null=True,blank=True,default=0)

    def __unicode__(self):
        return self.job_title

    class Meta:

        verbose_name = 'JobPosting'
        verbose_name_plural = 'JobPosting'

from jobseeker.models import Jobseeker
from employer.models import Recruiter

class RequestSend(models.Model):

    recruiter = models.ForeignKey(Recruiter)
    jobseeker = models.ForeignKey(Jobseeker)
    request_date = models.DateField('Requested Date',null=True, blank=True, auto_now_add=True)
    is_request = models.BooleanField('Requested', default=True)
    is_replied = models.BooleanField('Replied', default=False)
    is_delete = models.BooleanField('Delete', default=False)
    is_new = models.BooleanField('Is new Request', default=True)
    
    def __unicode__(self):
        return self.recruiter.company.company_name

    class Meta:

        verbose_name = 'Requestes'
        verbose_name_plural = 'Requestes'

class Reply(models.Model):

    request = models.ForeignKey(RequestSend)
    reply_date = models.DateField('Replied Date',null=True, blank=True, auto_now_add=True)
    is_delete = models.BooleanField('Delete', default=False)
    is_new = models.BooleanField('Is new Request', default=True)

    def __unicode__(self):
        return self.request.recruiter.company.company_name

    class Meta:

        verbose_name = 'Reply'
        verbose_name_plural = 'Reply'


class ContactUs(models.Model):

    name = models.CharField('Name', max_length=200, null=True, blank=True)
    mail = models.CharField('Email', max_length=200, null=True, blank=True)
    message = models.CharField('Message', max_length=300, null=True, blank=True)
    mobile =  models.CharField('Phone', max_length=200,null=True, blank=True)
    source = models.CharField('Source', max_length=300, null=True, blank=True)
    other = models.CharField('Other', max_length=300, null=True, blank=True)

    def __unicode__(self):
        return self.name


class CVRequest(models.Model):

    name = models.CharField('Name', max_length=200, null=True, blank=True)
    mail = models.CharField('Email', max_length=200, null=True, blank=True)
    mobile =  models.CharField('Phone', max_length=200,null=True, blank=True)

    def __unicode__(self):
        return self.name